#!/bin/bash


# ToDo : Convert to importutility later.
# shellcheck source=../utils/system
source "$BASH_PROFILE_PATH/utils/system"
# shellcheck source=../utils/string
source "$BASH_PROFILE_PATH/utils/string"
# shellcheck source=../utils/env
source "$BASH_PROFILE_PATH/utils/env"


# shellcheck source=./services
source "$BASH_PROFILE_PATH/sources/services"



# Check if the current directory is either
# 'newton' or newton<n> where n is a number
function dirismultienvnewton() {
	local regexNewtonLike='^newton$|^newton[1-9][0-9]*$'
	[[ $1 =~ $regexNewtonLike ]]
}


function enableDrawingsExports() {
  export ENABLE_THUMBNAIL_SERVICE=1
  export START_RENDERER_IN_MAIN_THREAD=1
  # disable if debugging thumbnails.
  export BTI_BLOCK_THUMBNAIL_CPP_SERVER_POOL=1
}


# Set CPP builder according to the platform
function platformspecificsettings() {
  local useclion
  useclion=$(env.readvarfromdisk REMEMBER_CLION_BUILD)
  if system.ismacos && ! string.equals "$useclion" "true"
  then
    echo "Using XCODEBUILD by default"
    unset CLIONBUILD
    export XCODEBUILD=1
  else # Assume Linux for now.
    echo "Using CLIONBUILD for building C++"
    unset XCODEBUILD
    export CLIONBUILD=1
  fi
}


# Unofficial exports
# ------------------
# Now when the environment should be set, some exports used by this script:
function exportAfterInitVariables() {
  local envNum
  envNum=$(env.getnumber)
  CURRENT_RELEASE=$(env.readvarfromdisk CURRENT_RELEASE)
  export CURRENT_RELEASE
  export LSB_MASTER=lsb/master
  export LSB_CURRENT_RELEASE=lsb/$CURRENT_RELEASE
  export GIT_MERGE_AUTOEDIT=no
  export RETRIEVAL_REPORT_WRITE_TO_DISK=1
  export PATH="$HOME/Library/Python/3.8/bin:${PATH}" # Mostly so that 'rbt' works.
  export btserverwebpath="$STAGE/WebSvc/logs/btserver.log"
  export btservermodpath="$STAGE/ModelingSvc/logs/btserver.log"
  export timerlogwebpath="$STAGE/WebSvc/logs/timer.log"
  export timerlogmodpath="$STAGE/ModelingSvc/logs/timer.log"
  export upgradelogwebpath="$STAGE/WebSvc/logs/upgrade.log"
  # Sometimes, for some reason the logs go in the logsDir_IS_UNDEFINED directory
  # No one seems to know the exact reason at the time of writing this.
  export undefinedbtserverwebpath="$STAGE/WebSvc/logsDir_IS_UNDEFINED/btserver.log"
  export undefinedbtservermodpath="$STAGE/ModelingSvc/logsDir_IS_UNDEFINED/btserver.log"
  export undefinedtimerlogwebpath="$STAGE/WebSvc/logsDir_IS_UNDEFINED/timer.log"
  export DEFAULT_GRUNT_SERVE_PORT="8000"
  export DEFAULT_ONSHAPE_PORT="8400"

  # Set GRUNT_SERVE_PORT according to the env number
  export GRUNT_SERVE_PORT=$((DEFAULT_GRUNT_SERVE_PORT+envNum))
  export ONSHAPE_PORT=$((DEFAULT_ONSHAPE_PORT+envNum))

  export CURRENT_BUILD_TOOLS_PATH="$ROOT_DIR"
  export JETTY_ARGS="jetty.ssl.port=$ONSHAPE_PORT"

  if isdebuggingdrawings
  then
    enableDrawingsExports
  fi
}

function __setupNewtonInternal() {
  source buildenv.bash
  exportAfterInitVariables
  platformspecificsettings
}

# Ensure we're in the newton directory
# or one of its subdirectories.
function ensurenewtondirectory() {
  if string.isemptyorblank "$REPO_NEWTON"
  then
    # Should be the case when we've just started the Terminal.
    local currentdirname
    currentdirname=$(system.dirnamefrompath "$(pwd)")
    if ! dirismultienvnewton "$currentdirname"
    then
      # $REPO_NEWTON is not set, and we are
      # also not in a newton/newton<n> like directory
      # assume newton '1'.
      cd "$HOME/repos/newton" || exit
    fi

    # now when a newton like directory is ensured,
    # call the buildenv.bash script
    __setupNewtonInternal
  else
    if ! string.contains "$(pwd)" "$REPO_NEWTON"
    then
      # $REPO_NEWTON is initialized but we're not in it or one of its subdirectories
      cd "$REPO_NEWTON" || exit
    fi

    if ! env.isInitialized
    then
      # In some cases we can have REPO_NEWTON etc. defined, but the build environment
      # is still not initialized. We need to call buildenv.bash in this case too.
      __setupNewtonInternal
    fi
  fi
}

# Terminal Shell should call this function to setup.
function setupnewton() {
  ensurenewtondirectory
}
