#!/bin/bash


# ToDo : Convert to importutility later.
# shellcheck source=../utils/system
source "$BASH_PROFILE_PATH/utils/system"
# shellcheck source=../utils/string
source "$BASH_PROFILE_PATH/utils/string"
# shellcheck source=../utils/env
source "$BASH_PROFILE_PATH/utils/env"


# shellcheck source=./services
source "$BASH_PROFILE_PATH/sources/services"
# shellcheck source=./settings-provider
source "$BASH_PROFILE_PATH/sources/settings-provider"


# Test if the given directory is a valid newton directory
# (e.g. of the format $HOME/repos/newton[0-9]*)
function isavalidnewtondirectory() {
  local directorypath="$1"
  if string.isemptyorblank "$directorypath"
  then
    directorypath="$(pwd)"
  fi

  local directoryCanonicalPath=""
  directoryCanonicalPath="$(system.getcanonicalpath "$directorypath")"

  if string.contains "$directoryCanonicalPath" "$(settings.getbaserepopath)"
  then
    local dirname=""
    dirname="$(system.dirnamefrompath "$directorypath")"
    if string.matchesRegex "$dirname" "^newton$|^newton[1-9][0-9]*$"
    then
      if calledfromterminal
      then
        print_success "Yes"
      fi
      return 0
    else
      if calledfromterminal
      then
        print_error "No"
      fi
      return 1
    fi
  else
    if calledfromterminal
    then
      print_error "No"
    fi
    return 1
  fi
}


# Set CPP builder according to the platform
function platformspecificsettings() {
  local useclion
  useclion=$(env.readvarfromdisk USE_CLION_INSTEAD_OF_XCODE)
  if system.ismacos && ! string.equals "$useclion" "true"
  then
    echo "Using XCODEBUILD by default"
    unset CLIONBUILD
    export XCODEBUILD=1
  else # Assume Linux for now.
    echo "Using CLIONBUILD for building C++"
    unset XCODEBUILD
    export CLIONBUILD=1
  fi
}


# Unofficial exports
# ------------------
# Now when the environment should be set, some exports used by this script:
function exportAfterInitVariables() {
  local envNum
  envNum=$(env.getnumber)
  CURRENT_RELEASE=$(env.readvarfromdisk CURRENT_RELEASE)
  export CURRENT_RELEASE
  export LSB_MASTER=lsb/master
  export LSB_CURRENT_RELEASE=lsb/$CURRENT_RELEASE
  export GIT_MERGE_AUTOEDIT=no
  export RETRIEVAL_REPORT_WRITE_TO_DISK=1
  export PATH="$HOME/Library/Python/3.8/bin:${PATH}" # Mostly so that 'rbt' works.

  if string.isnotemptyorblank "$STAGE"
  then
    export btserverwebpath="$STAGE/WebSvc/logs/btserver.log"
    export btservermodpath="$STAGE/ModelingSvc/logs/btserver.log"
    export timerlogwebpath="$STAGE/WebSvc/logs/timer.log"
    export timerlogmodpath="$STAGE/ModelingSvc/logs/timer.log"
    export upgradelogwebpath="$STAGE/WebSvc/logs/upgrade.log"
    # Sometimes, for some reason the logs go in the logsDir_IS_UNDEFINED directory
    # No one seems to know the exact reason at the time of writing this.
    export undefinedbtserverwebpath="$STAGE/WebSvc/logsDir_IS_UNDEFINED/btserver.log"
    export undefinedbtservermodpath="$STAGE/ModelingSvc/logsDir_IS_UNDEFINED/btserver.log"
    export undefinedtimerlogwebpath="$STAGE/WebSvc/logsDir_IS_UNDEFINED/timer.log"
  fi

  local defaultGruntServePort=$(env.getproperty DEFAULT_GRUNT_SERVE_PORT "8000")
  local defaultOnshapePort=$(env.getproperty DEFAULT_ONSHAPE_PORT "8400")

  # Set GRUNT_SERVE_PORT according to the env number
  export GRUNT_SERVE_PORT=$((defaultGruntServePort+envNum))
  export ONSHAPE_PORT=$((defaultOnshapePort+envNum))

  export CURRENT_BUILD_TOOLS_PATH="$ROOT_DIR"
  export JETTY_ARGS="jetty.ssl.port=$ONSHAPE_PORT"

  if settings.isservingonlan
  then
    echo "Serving webpack on LAN (call resetserveonlan to unset this persistent setting)"
    export NEWTON_WEBPACK_SERVE_ON_LAN=1
  else
    unset NEWTON_WEBPACK_SERVE_ON_LAN
  fi

  if settings.isdebuggingdrawings
  then
    __setdrawingsexports "true"
  fi
}

function __initializeNewtonInternal() {
  local mode="$1"
  # Do not source buildenv.bash in 'light' mode.
  if string.isemptyorblank "$mode" || ! string.equals "$mode" "light"
  then
    source buildenv.bash
  fi

  exportAfterInitVariables
  platformspecificsettings
}

# Ensure we're in the newton directory
# or one of its subdirectories.
function ensurenewtondirectory() {
  local mode="$1"

  if string.isemptyorblank "$REPO_NEWTON"
  then
    # Should be the case when we've just started the Terminal.
    if ! isavalidnewtondirectory "$(pwd)"
    then
      # $REPO_NEWTON is not set, and we are
      # also not in a newton/newton<n> like directory
      # assume newton '1'.
      cd "$(system.getkeyvaluefromfile "$BASH_PROFILE_PATH/settings" "BASE_REPO_PATH")/newton" || exit
    fi

    # now when a newton like directory is ensured,
    # call the buildenv.bash script
    __initializeNewtonInternal "$mode"
  else
    if ! string.contains "$(pwd)" "$REPO_NEWTON"
    then
      # $REPO_NEWTON is initialized but we're not in it or one of its subdirectories
      cd "$REPO_NEWTON" || exit
    fi

    if ! env.isInitialized
    then
      # In some cases we can have REPO_NEWTON etc. defined, but the build environment
      # is still not initialized. We need to call buildenv.bash in this case too.
      __initializeNewtonInternal "$mode"
    fi
  fi
}

# Terminal Shell should call this function to setup.
function initializenewton() {
  ensurenewtondirectory
}

function initializenewtonlight() {
  ensurenewtondirectory "light"
}
