#!/bin/bash

# ToDo : Convert to importutility later.
# shellcheck source=../utils/system
source "$BASH_PROFILE_PATH/utils/system"
# shellcheck source=../utils/string
source "$BASH_PROFILE_PATH/utils/string"
# shellcheck source=../utils/env
source "$BASH_PROFILE_PATH/utils/env"
# shellcheck source=../utils/docker
source "$BASH_PROFILE_PATH/utils/docker"

# shellcheck source=./services
source "$BASH_PROFILE_PATH/sources/services"
# shellcheck source=./newton
source "$BASH_PROFILE_PATH/sources/newton"
# shellcheck source=./settings-provider
source "$BASH_PROFILE_PATH/sources/settings-provider"


# Multi-env aware
function getbelcadpid() {
  # PS ToDo: This might be 'wrong'
  # if it solely depends on
  # the $STAGE env variable, unless
  # the env.isInitialized function returns true.
  if string.isemptyorblank "$STAGE"
  then
    echo ""
    return 1
  fi

  local jettypid
  # shellcheck disable=SC2009
  jettypid=$(ps -ef | grep jetty | grep "$STAGE/" | awk '{print $2}')
  echo "$jettypid"
}


# Multi-env aware
# Prints an output (True/False) only when called
# directly from the Terminal (else returns true/false)
function isonshapeserverrunning() {
  local jettypid
  jettypid=$(getbelcadpid)
  if calledfromterminal
  then
    if string.isemptyorblank "$jettypid"
    then
      print_error "No."
    else
      if isvalidonshapeserver
      then
        print_success "Yes, PID : $jettypid"
      else
        print_error "Yes, PID : $jettypid, but it's NOT a valid connection"
      fi
    fi
  fi

  string.isnotemptyorblank "$jettypid"
}


# Starts both the Onshape (belcad) server
# and calls grunt start to start the
# webpack compiler for incremental Typescript
# development and debugging
function startservers() {
  ensurenewtondirectory
  if ! docker.isrunning
  then
    # startServices is supposed to start
    # Docker as well if not running
    startServices
  fi

  if isonshapeserverrunning
  then
    echo "Onshape server is already running"
  else
    echo "Onshape server not already running, starting it now"
    startbelcad
    if ! system.waslastcommandsuccessful
    then
      print_error "Error: Could not start Onshape server. Not starting quickServer"
      return 1
    fi
  fi

  if settings.isdebuggingdrawings
  then
    if isdrawingservicerunning
    then
      echo "Drawings server is already running"
    else
      startDrawingDocker skipupdate
      if ! system.waslastcommandsuccessful
      then
        print_error "Error: Could not start Drawings server."
        return 1
      fi
    fi
  fi

  if settings.isusingquickserve
  then
    if isquickserverunning
    then
      echo "quickServe is already running"
    else
      echo "quickServe is not already running, starting it now"
      quickserve
    fi
  fi
}



function getquickserveport() {
  # Do not remove the env variable,
  # it's used by official build tools scripts
  echo "$GRUNT_SERVE_PORT"
}

function getquickservepid() {
  local port
  port=$(getquickserveport)
  if string.isemptyorblank $port
  then
    echo ""
    return 1
  fi

  # Find node processes listening on the port
  # This handles all IP binding patterns: *:port, 127.0.0.1:port, 0.0.0.0:port, etc.
  # lsof output format: COMMAND PID USER ... TCP *:8005 (LISTEN)
  # We filter for node processes in the COMMAND column and LISTEN state
  local pid
  pid=$(lsof -iTCP:$port -n -P 2> /dev/null | awk '/^node/ && /LISTEN/ {print $2}' | head -n 1)

  echo "$pid"
}

function isquickserverunning() {
  local pid
  pid=$(getquickservepid)

  if calledfromterminal
  then
    if string.isemptyorblank "$pid"
    then
      echo "No."
    else
      echo "Yes, PID : $pid"
    fi
  fi

  string.isnotemptyorblank "$pid"
}


# shellcheck disable=SC2120
function fstopquickserve() {
  local pid
  pid=$(getquickservepid)
  if ! string.isemptyorblank "$pid"
  then
    killprocessid "$pid" "quickserve" "$1" # this optional argument can be "nosleep"
  else
    echo "Didn't find quickserve process to kill"
  fi
}

function fstopbelcad() {
  # Consider using this instead, which is multi-env aware: checkServices -s websvc
  local jettypid
  jettypid=$(getbelcadpid)
  if ! string.isemptyorblank "$jettypid"
  then
    killprocessid "$jettypid" "jetty" "$1" # this optional argument can be "nosleep"
    return 0
  else
    echo "Didn't find onshape process to kill"
    return 1
  fi
}


function stopservers() {
  fstopbelcad "nosleep"
  if settings.isdebuggingdrawings
  then
    stopDrawingDocker
  fi

  if settings.isusingquickserve
  then
    # Stop the grunt start started webpack server.
    fstopquickserve
  fi
}

function restartservers() {
  stopservers
  startservers
}


function getbsservers() {
  # shellcheck disable=SC2009
  ps -ef | grep "BSServer" | grep "$STAGE/" | awk '{print $2}'
}

function killbsservers() {
  getbsservers | xargs kill
}

function restartbelcad() {
  fstopbelcad

  if ! docker.isrunning
  then
    startServices
  fi

  startbelcad
}

function quickserve() {
  ensurenewtondirectory

  # Start actual 'quick' serve (webpack) process
  nohup rex start > .newtonwebpacklog 2>&1 &
  disown  # Detach the background job from shell job control

  local quickserveport=$(getquickserveport)
  echo "quickserve started, waiting for it to be ready to serve the page on $quickserveport"

  # while ! nc -z "127.0.0.1" $quickserveport; do
  #   sleep 1
  # done

  while [ ! -f .newtonwebpacklog ]
  do
    sleep 1
  done

  echo "Waiting for webpack to compile successfully..."
  tail -n 0 -F .newtonwebpacklog | while read line
  do
    echo "$line"
    if echo "$line" | grep -q "compiled successfully in"; then
      echo "Webpack compiled successfully."
      break
    fi
  done
}

function restartquickserve() {
  fstopquickserve
  quickserve
}


# Sometimes the process itself is running,
# but it's non-functional. Validate it. Thanks PT Rajkumar
# for the trick to validate.
# ToDo : Sometimes the validation gets stuck. Check it
function isvalidonshapeserver() {
  local output
  output=$(curl -s "https://multienv$(env.getnumber).onshape.io/api/build" | grep Manifest-Version)
  if calledfromterminal
  then
    if string.isemptyorblank "$output"
    then
      print_error "No."
    else
      print_success "Yes"
    fi
  fi

  string.isnotemptyorblank "$output"
}



function areserversrunning() {
  local hasError="false"

  echo -n "Onshape server is "
  if ! isonshapeserverrunning
  then
    hasError="true"
    print_error "NOT running"
  else
    # Check if the Onshape server is 'valid'
    if ! isvalidonshapeserver
    then
      hasError="true"
      print_error "running, but not functioning"
      return 1
    else
      print_success "running"
    fi
  fi

  if settings.isusingquickserve
  then
    echo -n "quickServe is "
    if ! isquickserverunning
    then
      hasError="true"
      print_error "NOT running"
    else
      print_success "running"
    fi
  fi

  if settings.isdebuggingdrawings
  then
    echo -n "Drawings server is "
    if ! isdrawingservicerunning
    then
      hasError="true"
      print_error "NOT running"
    else
      print_success "running"
    fi
  fi

  if string.equals $hasError "false"
  then
    # echo "All selected servers are running."
    return 0 # success
  else
    return 1
  fi
}
