#!/bin/bash

# ToDo : Convert to importutility later.
# shellcheck source=../utils/system
source "$BASH_PROFILE_PATH/utils/system"
# shellcheck source=../utils/string
source "$BASH_PROFILE_PATH/utils/string"
# shellcheck source=../utils/env
source "$BASH_PROFILE_PATH/utils/env"

# shellcheck source=./docker
source "$BASH_PROFILE_PATH/sources/docker"
# shellcheck source=./services
source "$BASH_PROFILE_PATH/sources/services"
# shellcheck source=./newton
source "$BASH_PROFILE_PATH/sources/newton"


# Multi-env aware
function getbelcadpid() {
  local jettypid
  # shellcheck disable=SC2009
  jettypid=$(ps -ef | grep jetty | grep "$STAGE/" | awk '{print $2}')
  echo "$jettypid"
}


# Multi-env aware
# Prints an output (True/False) only when called
# directly from the Terminal (else returns true/false)
function isonshapeserverrunning() {
  local jettypid
  jettypid=$(getbelcadpid)
  if calledfromterminal
  then
    if string.isemptyorblank "$jettypid"
    then
      print_error "No."
    else
      if isvalidonshapeserver
      then
        print_success "Yes, PID : $jettypid"
      else
        print_error "Yes, PID : $jettypid, but it's NOT a valid connection"
      fi
    fi
  fi

  string.isnotemptyorblank "$jettypid"
}


# Starts both the Onshape (belcad) server
# and calls grunt start to start the
# webpack compiler for incremental Typescript
# development and debugging
function startservers() {
  ensurenewtondirectory
  if ! docker.isrunning
  then
    # startServices is supposed to start
    # Docker as well if not running
    startServices
  fi

  if isonshapeserverrunning
  then
    echo "Onshape server is already running"
  else
    echo "Onshape server not already running, starting it now"
    startbelcad
    if ! system.waslastcommandsuccessful
    then
      print_error "Error: Could not start Onshape server. Not starting quickServer"
      return 1
    fi
  fi

  if isdebuggingdrawings
  then
    if isdrawingservicerunning
    then
      echo "Drawings server is already running"
    else
      startDrawingDocker skipupdate
      if ! system.waslastcommandsuccessful
      then
        print_error "Error: Could not start Drawings server."
        return 1
      fi
    fi
  fi

  if isquickserverunning
  then
    echo "quickServe is already running"
  else
    echo "quickServe is not already running, starting it now"
    quickserve
  fi
}



function getquickserveport() {
  echo "$GRUNT_SERVE_PORT"
}

function getquickservepid() {
  local port
  port=$(getquickserveport)
  local searchString="node.*127\.0\.0\.1:$port.*LISTEN"

  local pid
  pid=$(lsof -iTCP -n -P 2> /dev/null | grep "$searchString" | awk '{print $2}')
  echo "$pid"
}

function isquickserverunning() {
  local pid
  pid=$(getquickservepid)

  if calledfromterminal
  then
    if string.isemptyorblank "$pid"
    then
      echo "No."
    else
      echo "Yes, PID : $pid"
    fi
  fi

  string.isnotemptyorblank "$pid"
}


# shellcheck disable=SC2120
function fstopquickserve() {
  local pid
  pid=$(getquickservepid)
  if ! string.isemptyorblank "$pid"
  then
    killprocessid "$pid" "quickserve" "$1" # this optional argument can be "nosleep"
  else
    echo "Didn't find quickserve process to kill"
  fi
}

function fstopbelcad() {
  # Consider using this instead, which is multi-env aware: checkServices -s websvc
  local jettypid
  jettypid=$(getbelcadpid)
  if ! string.isemptyorblank "$jettypid"
  then
    killprocessid "$jettypid" "jetty" "$1" # this optional argument can be "nosleep"
    return 0
  else
    echo "Didn't find onshape process to kill"
    return 1
  fi
}


function stopservers() {
  fstopbelcad "nosleep"
  if isdebuggingdrawings
  then
    stopDrawingDocker
  fi
  # Stop the grunt start started webpack server.
  fstopquickserve
}

function restartservers() {
  stopservers
  startservers
}


function getbsservers() {
  # shellcheck disable=SC2009
  ps -ef | grep "BSServer" | grep "$STAGE/" | awk '{print $2}'
}

function killbsservers() {
  getbsservers | xargs kill
}

function restartbelcad() {
  fstopbelcad

  if ! docker.isrunning
  then
    startServices
  fi

  startbelcad
}

function quickserve() {
  ensurenewtondirectory
  nohup rex start > .newtonwebpacklog 2>&1 &
}

function restartquickserve() {
  fstopquickserve
  quickserve
}


# Sometimes the process itself is running,
# but it's non-functional. Validate it. Thanks PT Rajkumar
# for the trick to validate.
# ToDo : Sometimes the validation gets stuck. Check it
function isvalidonshapeserver() {
  local output
  output=$(curl -s "https://multienv$(env.getnumber).onshape.io/api/build" | grep Manifest-Version)
  if calledfromterminal
  then
    if string.isemptyorblank "$output"
    then
      print_error "No."
    else
      print_success "Yes"
    fi
  fi

  string.isnotemptyorblank "$output"
}



function areserversrunning() {
  local hasError="false"

  echo -n "Onshape server is "
  if ! isonshapeserverrunning
  then
    hasError="true"
    print_error "NOT running"
  else
    # Check if the Onshape server is 'valid'
    if ! isvalidonshapeserver
    then
      hasError="true"
      print_error "running, but not functioning"
      return 1
    else
      print_success "running"
    fi
  fi

  echo -n "quickServe is "
  if ! isquickserverunning
  then
    hasError="true"
    print_error "NOT running"
  else
    print_success "running"
  fi

  if isdebuggingdrawings
  then
    echo -n "Drawings server is "
    if ! isdrawingservicerunning
    then
      hasError="true"
      print_error "NOT running"
    else
      print_success "running"
    fi
  fi

  if string.equals $hasError "false"
  then
    # echo "All selected servers are running."
    return 0 # success
  else
    return 1
  fi
}



function setserveonlan() {
  if string.equals "$1" "false"
  then
    unset NEWTON_WEBPACK_SERVE_ON_LAN
  else
    export NEWTON_WEBPACK_SERVE_ON_LAN=1
  fi
  restartquickserve
}


function resetserveonlan() {
  setserveonlan "false"
}
