#!/bin/bash

# utils
# ToDo : Convert to importutility later.
# shellcheck source=../utils/system
source "$BASH_PROFILE_PATH/utils/system"
# shellcheck source=../utils/string
source "$BASH_PROFILE_PATH/utils/string"
# shellcheck source=../utils/env
source "$BASH_PROFILE_PATH/utils/env"

# sources
# shellcheck source=./docker
source "$BASH_PROFILE_PATH/sources/docker"


# Start required services for the Onshape server
# and newton to run (not the server itself, use
# the functions defined in ./servers for that).
# Also starts Docker if it is not already running.
function startServices() {
  if ! docker.isrunning
  then
    echo "Starting Docker process as it was not found to be running"
    docker.startapp
  else
    echo "Docker found to be running"
  fi
  # Actually start the services now when Docker is confirmed to be running
  btEnvUp
}


function stopServices() {
  btEnvDown
}

function setdebuggingdrawings() {
  local DEBUGGING_DRAWINGS=$1
  if string.isemptyorblank "$DEBUGGING_DRAWINGS"
  then
    DEBUGGING_DRAWINGS="true"
  fi

  if string.equals "$DEBUGGING_DRAWINGS" "true"
  then
    enableDrawingsExports
  fi

  env.writevartodisk DEBUGGING_DRAWINGS
}


function isdebuggingdrawings() {
  local DEBUGGING_DRAWINGS
  DEBUGGING_DRAWINGS=$(env.readvarfromdisk DEBUGGING_DRAWINGS)
  string.equals "$DEBUGGING_DRAWINGS" "true"
}

# Stop all services for 'this' environment
# something which stopServices doesn't.
# But will ALSO affect other environment, as
# there are shared services like zookeeper.
function stopallservices() {
  # shellcheck disable=SC1091
  source "${TOOLS_BASH}/lib/docker/stopDockerContainer.bash"
  stopServices
  stopZookeeperIfRunning
  stopDockerContainer dns-proxy
  stopDockerContainer "$(getContainerName https)"
  if isdebuggingdrawings
  then
    stopDrawingDocker
  fi
}

function isASharedService() {
  local serviceName="$1"
  string.equals "$serviceName" "zookeeper" || string.equals "$serviceName" "https" || string.equals "$serviceName" "mock-services"
}

# Get only the suffix if an argument is not provided
# otherwise return the full service name with suffix
function getEnvServiceSuffixOrFullServiceName() {
  local serviceName="$1"
  local envNum=$(env.getnumber)
  if isASharedService "$serviceName" || string.equals "$envNum" "0"
  then
    echo "$serviceName"
  else
    echo "${serviceName}_myenv${envNum}"
  fi
  return 0
}

function declareAllServices() {
  # In a rough order of core to non-core services
  ALL_SERVICES_AND_COMMANDS=(
    "memcached<envsuffix>: startMemcache, "
    "mongod<envsuffix>: startMongod, "
    "rabbitmq<envsuffix>: startRabbitMQServer, "
    "xenon<envsuffix>: startDrawingDocker, stopDrawingDocker"
    "zookeeper: startZookeeper, stopZookeeperIfRunning"
    "https: startHTTPS, "
    "mock-services: startMockServices, stopMockServices"
    "kibana<envsuffix>: startKibana, stopKibana"
    "fgs<envsuffix>: startFgs, stopFgs"
    "cache-ng<envsuffix>: startCacheNg, stopCacheNg"
    "app-qa<envsuffix>: startAppQA, stopAppQA"
    "elasticsearch<envsuffix>: startElasticsearch, stopElasticsearch"
  )
}

function getStartFunctionNameForService() {
  local inputServiceName="$1"
  
  # Ensure the array is declared
  declareAllServices
  
  # Loop over all entries in ALL_SERVICES_AND_COMMANDS
  for entry in "${ALL_SERVICES_AND_COMMANDS[@]}"; do
    # Extract key (before colon) and value (after colon)
    local key="${entry%%:*}"
    local value="${entry#*:}"
    
    # Determine the full service name
    local fullServiceName
    if string.contains "$key" "<envsuffix>"; then
      # Extract base service name (before <envsuffix>)
      local baseServiceName="${key%%<envsuffix>}"
      # getEnvServiceSuffixOrFullServiceName returns the full service name with suffix
      # when the base service name is provided.
      fullServiceName=$(getEnvServiceSuffixOrFullServiceName "$baseServiceName")
    else
      # For shared services, the key itself is the full service name
      fullServiceName="$key"
    fi
    
    # If the full service name matches the input, extract and return the start function
    if string.equals "$fullServiceName" "$inputServiceName"; then
      # Split value on comma and get the first part (start function)
      local startFunction="${value%%,*}"
      # Trim spaces and return
      echo "$(string.trim "$startFunction")"
      return 0
    fi
  done
  
  # Service not found
  return 1
}

function callStartFunctionForService() {
  local inputServiceName="$1"
  
  # Get the start function name for the service
  local startFunctionName
  startFunctionName=$(getStartFunctionNameForService "$inputServiceName")
  
  # Check if the function is defined
  if ! isFunctionDefined "$startFunctionName"
  then
    echo "Error: Could not find start function for service '$inputServiceName'" >&2
    return 1
  fi
  
  # Call the start function
  "$startFunctionName"
}

function declareEssentialServices() {
  # This if else is in this form mostly because I don't know how to dynamically add
  # just one element in the array :), but it's ok for now.
  ESSENTIAL_SERVICES_AND_COMMANDS=("memcached: startMemcache" "mongod: startMongod" "rabbitmq: startRabbitMQServer")
  if isdebuggingdrawings
  then
    ESSENTIAL_SERVICES_AND_COMMANDS=("memcached: startMemcache" "mongod: startMongod" "rabbitmq: startRabbitMQServer" "xenon: startDrawingDocker")
  fi
}


# Another version of the official 'checkServices'. Tells you if
# the absolutely essential services required for running Onshape
# properly are running or not, so that you don't have to
# look at all of them.
function checkessentialservices() {
  local output
  output=$(checkServices)

  declareEssentialServices

  local allRunning="true"
  for entry in "${ESSENTIAL_SERVICES_AND_COMMANDS[@]}" ; do
      service=${entry%%:*}
      local serviceRunning
      serviceRunning=$(echo "$output" | grep "$service.. ok docker container")

      if string.isemptyorblank "$serviceRunning"
      then
        print_error "Essential service $service is not running"
        allRunning="false"
      fi
  done

  if string.equals $allRunning "true"
  then
    print_success "All essential services are running"
    return 0
  else
    return 1
  fi
}


# Arguments:
  # 1. "true" / "false" - autoFix services.
# shellcheck disable=SC2120
function fastcheckessentialservices() {
  local envString=""
  local autoFix="$1"
  local autoFixString=""
  local envNumber
  envNumber=$(env.getnumber)

  if string.equals "$autoFix" "true"
  then
    autoFixString=", starting it"
  fi

  if ! string.equals "$envNumber" "0"
  then
    envString="_myenv$envNumber"
  fi

  declareEssentialServices

  local runningServicesArray=( $(docker ps --format '{{.Names}}') )
  local allRunning="true"

  # Zookeeper is shared between all environments, check if it's running
  # shellcheck disable=SC2199
  if [[ ! " ${runningServicesArray[@]} " =~ " zookeeper " ]]
  then
    print_error "Essential service zookeeper is not running$autoFixString"
    if string.equals "$autoFix" "true"
    then
      startZookeeper
    fi
    allRunning="false"
  fi

  for entry in "${ESSENTIAL_SERVICES_AND_COMMANDS[@]}" ; do
      service=${entry%%:*}
      startCommandName=${entry#*: }
      # shellcheck disable=SC2199
      # shellcheck disable=SC2076
      if [[ ! " ${runningServicesArray[@]} " =~ " $service$envString " ]]
      then
        print_error "Essential service $service is not running$autoFixString"
        if string.equals "$autoFix" "true"
        then
          $startCommandName # start the service.
        fi

        allRunning="false"
      fi
  done

  if string.equals $allRunning "true"
  then
    print_success "All essential services are running"
    return 0
  else
    # All services were not running, but may have been started now.
    if string.equals "$autoFix" "true"
    then
      if fastcheckessentialservices #check if services are running now
      then
        print_success "Essential services were not running but have been fixed"
        return 0
      else
        print_error "Essential services could not be fixed"
        return 1
      fi
    else
      return 1
    fi
  fi
}


function fixessentialservices() {
  fastcheckessentialservices "true" #auto-fix
}



function isdrawingservicerunning() {
  source "${TOOLS_BASH}/lib/docker/isDrawingDockerRunning.bash"
  isDrawingDockerRunning
}

function monitorServices() {
  while fastcheckessentialservices; do
    sleep 5
  done

  beep;beep
  say "Essential services have stopped"
}
