#!/bin/bash

#Common

importutility string
importutility system

# By default Bash terminal doesn't auto complete
# function/command names when they're followed by the
# type command. This is to enable that.
__type_command_completion() {
    # Get the current word being typed
    local cur="${COMP_WORDS[COMP_CWORD]}"

    # Generate a list of all completion types that 'type' accepts
    # -a: aliases, -k: keywords, -A function: functions, -b: builtins, -c: commands
    COMPREPLY=( $(compgen -a -k -A function -b -c -- "$cur") )
}

# Apply the custom completion function to the 'type' command
complete -F __type_command_completion type

# Usage : 	findbyname <filename to search in current directory>
# 			Or
#			findbyname <filename to search> <directory>
function findbyname() {
	if [ -z "$1" ]
	then
		echo "Usage: \nfindbyname <filename to search in current directory>\n or\nfindbyname <filename to search> <directory>"
		return
	fi

	local filename="$1"
	local directory="$2"

	if [ -z "$directory" ]
	then
	 	# Assume only filename specified, search in current directory
		directory="."
	fi

	find "$directory" -name "$filename" 2>/dev/null
}

# alias sublime='open -a "/Applications/Sublime Text.app"'
# alias bbedit='open -a /Applications/BBEdit.app'
# alias z='open -a /Applications/Zed.app/'

# Text editors
# Write your preferred text editor of choice, in the order of preference
# List of their intended aliases and their app path to search. The first preferred editor
# to find would be set as the command `texteditor`, and you can also just call `edit`
# to use it.
PREFERRED_EDITORS_ARR=(
    "sublime: /Applications/Sublime Text.app"
    "bbedit: /Applications/BBEdit.app"
    "z: /Applications/Zed.app"
)

for editor in "${PREFERRED_EDITORS_ARR[@]}" ; do
    aliasName=${editor%%:*}
    path=${editor#*: }
    if system.direxists "$path"
    then
        alias $aliasName="open -a \"$path\""
        # If the texteditor alias is still not assigned, do it now.
        if string.isemptyorblank "$(command -v texteditor)"
        then
            alias texteditor="$aliasName"
        fi
    fi
done

# If none of the preferred editors are found:
if string.isemptyorblank "$(command -v texteditor)"
then
    alias texteditor='nano'
fi

function edit() {
    system.createfileifdoesnotexist "$1"
    texteditor $1
}

function color.red() {
    tput setaf 1
}

function color.green() {
    tput setaf 2
}

function color.reset() {
    tput sgr0
}

function print_error() {
  color.red
  echo "$@" >&2
  color.reset
}

function print_success() {
  color.green
  echo "$@"
  color.reset
}

function print_nonewline() {
  echo -n "$@"
}

# Send the message as an argument.
function user_agrees_to() {
    local message="$1"
    local response

    while true; do
        read -p "$message (y/n): " response
        case "$response" in
            [yY])
                return 0
                ;;
            [nN])
                return 1
                ;;
            *)
                echo "Please enter y or n."
                ;;
        esac
    done
}

# Test if a function is called directly
# from terminal or from another function.
function calledfromterminal() {
  # ${FUNCNAME[2]} represents the caller name of *this* function.
  # Empty if caller was called directly from terminal.
  #echo "${FUNCNAME[*]}"
  (string.isemptyorblank "${FUNCNAME[2]}")
}

alias te='texteditor'
alias editor='texteditor'
alias bundleid='findappbundleid'
alias appbundleid='findappbundleid'

# Git
## Auto Completion
## Please ensure bash-completion is installed by calling
## brew install bash-completion
[ -f /usr/local/etc/bash_completion ] && . /usr/local/etc/bash_completion

# IDEs
alias wstorm='webstorm'
alias inteli='idea' # Yes, wrong spelling.
alias intelli='idea'
alias intellij='idea'

# Others
alias python='/usr/bin/python3'
alias findfile='findbyname'
alias cd..='cd ..'
alias cd...='cd ../..'
alias print='echo'
