#!/bin/bash

#Common

importutility string
importutility system

# Usage : 	findbyname <filename to search in current directory>
# 			Or
#			findbyname <filename to search> <directory>
function findbyname() {
	if [ -z "$1" ]
	then
		echo "Usage: \nfindbyname <filename to search in current directory>\n or\nfindbyname <filename to search> <directory>"
		return
	fi

	local filename="$1"
	local directory="$2"

	if [ -z "$directory" ]
	then
	 	# Assume only filename specified, search in current directory
		directory="."
	fi

	find "$directory" -name "$filename" 2>/dev/null
}

function gitsetglobalignorefile() {
	if [ -z "$1"]
	then
		git config --global core.excludesfile $globalgitignorefile
	else
		git config --global core.excludesfile $1
	fi
}

# alias sublime='open -a "/Applications/Sublime Text.app"'
# alias bbedit='open -a /Applications/BBEdit.app'
# alias z='open -a /Applications/Zed.app/'

# Text editors
# Write your preferred text editor of choice, in the order of preference
# List of their intended aliases and their app path to search
PREFERRED_EDITORS_ARR=(
    "sublime: /Applications/Sublime Text.app"
    "bbedit: /Applications/BBEdit.app"
    "z: /Applications/Zed.app"
)

for editor in "${PREFERRED_EDITORS_ARR[@]}" ; do
    aliasName=${editor%%:*}
    path=${editor#*: }
    if system.direxists "$path"
    then
        echo "alias is $aliasName and path is $path"
        alias $aliasName="open -a \"$path\""
        # If the texteditor alias is still not assigned, do it now.
        if string.isemptyorblank "$(command -v texteditor)"
        then
            alias texteditor="$aliasName"
        fi
    fi
done

# if system.direxists "/Applications/Zed.app"
# then
#     alias texteditor='zed'
# elif system.direxists "/Applications/BBEdit.app"
# then
#     alias texteditor='bbedit'
# elif system.direxists "/Applications/Sublime Text.app"
# then
#     alias texteditor='sublime'
# else
#     alias texteditor='nano'
# fi

alias texteditor='sublime'

function edit() {
    system.createfileifdoesnotexist "$1"
    texteditor $1
}

alias te='texteditor'
alias editor='texteditor'
alias bundleid='findappbundleid'
alias appbundleid='findappbundleid'
alias cputemp='sudo powermetrics --samplers smc |grep -i "CPU die temperature"'

# Karabiner Elements
export karabinerconfigfile=$HOME/.config/karabiner/karabiner.json
alias karabinerconfig='texteditor "$karabinerconfigfile"'
alias openkarabinerconfig='edit "$karabinerconfigfile"'

# Git
## Auto Completion
## Please ensure bash-completion is installed by calling
## brew install bash-completion
[ -f /usr/local/etc/bash_completion ] && . /usr/local/etc/bash_completion

## Ignore
export globalgitignorefile=$HOME/.gitignore
alias opengitglobalignorefile='edit $globalgitignorefile'
alias openglobalgitignorefile='opengitglobalignorefile'
alias opengitignorefile='opengitglobalignorefile'

# IDEs
alias wstorm='webstorm'
alias inteli='idea' # Yes, wrong spelling.
alias intelli='idea'
alias intellij='idea'

# Others
alias python='/usr/bin/python3'
alias findfile='findbyname'
alias cd..='cd ..'
alias cd...='cd ../..'
