#!/bin/bash

# Official exports:
# -----------------
# CPP compiler cache
export USE_CCACHE=1

# Debug cpp build
export RELEASE=0

# Measure load times in viewer (can view in timer.log)
export BTI_ENABLE_TIMERS=1

# So that BSServer doesn't time out so early
export BTI_DISABLE_HEARTBEATS=1

# # So that thumbnails are generated in the dev environment (off by default)
# # Remove if not needed.
# export ENABLE_THUMBNAIL_SERVICE=1

# # For creating drawings shaded view (BEL-216201)
# export START_RENDERER_IN_MAIN_THREAD=1


# If debugging BSServer, cut down on the number of BSServers available to attach to
# ****** CAUTION: REMOVE WHEN WORKING WITH THUMBNAILS, otherwise it won't create Thumbnail
# cpp server pool ******
export BTI_BLOCK_THUMBNAIL_CPP_SERVER_POOL=1

# Remove unnecessary deprecation warning
export BASH_SILENCE_DEPRECATION_WARNING=1

# Improve artifactory download performance from S3, but sometimes causes other problems. Use only when
# facing problem with the default region (which is typically us-west-2)
#export OBJECT_STORE_REPO_REGION=ap-south-1

#export HOST_PROPERTIES_PRIVATEIP="$(dockerCreateLoopbackAlias)"

# Give more memory to Onshape server to be able to open bigger documents
export JAVA_MAX_MEMORY_MB=8192

# This is only an issue if you usually extract std from stacks and upgrade has to process lot of std versions
# In that case, there might be out of memory problems while building java
export UPGRADE_MAX_MEMORY_GB=8

# Use jaeger for local tracing instead of SignalFx:
export DEV_SIGNALFX_TRACING=2

# Dev Tools Path
export DEV_TOOLS=$HOME/repos/onshape-dev-tools

# Do not store command in the bash history if it's prefixed with a space
export HISTCONTROL=ignoreboth

# Others
#set -o nounset # Make the script fail if trying to access an unset variable.


# Import Utility modules
importutility string
importutility system
importutility git
importutility rbt
importutility general
importutility env


# Import sources
# shellcheck source=../sources/env
source "$BASH_PROFILE_PATH/sources/env"
# shellcheck source=../sources/services
source "$BASH_PROFILE_PATH/sources/services"
# shellcheck source=../sources/docker
source "$BASH_PROFILE_PATH/sources/docker"
# shellcheck source=../sources/servers
source "$BASH_PROFILE_PATH/sources/servers"
# shellcheck source=../sources/newton
source "$BASH_PROFILE_PATH/sources/newton"


function setclionbuild() {
  if string.isemptyorblank "$1" || string.equals "$1" "true"
  then
    local REMEMBER_CLION_BUILD="true"
    echo "Will choose CLION for building cpp code"
    env.writevartodisk REMEMBER_CLION_BUILD
    platformspecificsettings
  else
    resetclionbuild
  fi
}

function resetclionbuild() {
  echo "Removing clion build override, your platform specific default will be used"
  system.removevarfromdisk REMEMBER_CLION_BUILD $(env.getnumber)
  platformspecificsettings
}

function setrelease() {
  if string.equals $1 "0"
  then
    export RELEASE=0
    echo "Set to build in debug mode"
  else #empty or any other argument.
    export RELEASE=1
    echo "Set to build in release mode"
  fi
}

function setdebug() {
  if string.equals $1 "0"
  then
    export RELEASE=1
    echo "Set to build in release mode"
  else #empty or any other argument.
    export RELEASE=0
    echo "Set to build in debug mode"
  fi
}


function refreshcurrentreleasebranch() {
  ensurenewtondirectory
  local arg="$1"
  local latestremoterelease=""
  if string.equals "$arg" "--slow" || string.equals "$arg" "--force" || string.equals "$arg" "--remote" || string.equals "$arg" "-f" || string.equals "$arg" "-r"
  then
    echo "Fetching latest current release branch from the remote repository ..."
    local successful="false"
    local branchref=$(git ls-remote -q | grep -E "refs/heads/rel-\d+\.\d+$" | awk '{print $2}' | sort -V | tail -n 1)
    if string.isnotemptyorblank "$branchref"
    then
      latestremoterelease=$(string.simplereplace "$branchref" "refs/heads/" "")
      if string.beginswith "$latestremoterelease" "rel-"
      then
        successful="true"
      fi
    fi

    if string.equals "$successful" "false"
    then
      print_error "Could not find latest remote release branch. Please check if you're in the correct directory and git is working as expected."
      return 1
    fi
  else
    latestremoterelease=$(git branch -r | grep -E "origin/rel-\d+\.\d+$" | sort -V | tail -n 1)
  fi

  if ! system.waslastcommandsuccessful || string.isemptyorblank $latestremoterelease
  then
    print_error "Could not find latest remote release branch. Please check if you're in the correct directory and git is working as expected."
    return 1
  fi

  CURRENT_RELEASE=$(string.simplereplace $latestremoterelease "origin/" "")
  # Refresh the current lsb release branch as well.
  LSB_CURRENT_RELEASE=lsb/$CURRENT_RELEASE
  echo "CURRENT_RELEASE set to $CURRENT_RELEASE"

  # Write current release to a file
  env.writevartodisk CURRENT_RELEASE
}

function debugstaging() {
  #Try to debug staging
  export PROXY_TARGET_HOST='https://staging.dev.onshape.com'
  unset HOST_PROPERTIES_PRIVATEIP
  unset HOST_PROPERTIES_HOSTNAME
  echo "REMEMBER TO CLOSE THE TERMINAL AFTER THIS SESSION, OR CALLING source buildenv.bash AGAIN WHEN YOU'RE DONE"
  grunt quickServe
}

function debugdemoc() {
  #Try to debug staging
  export PROXY_TARGET_HOST='https://demo-c.dev.onshape.com'
  unset HOST_PROPERTIES_PRIVATEIP
  unset HOST_PROPERTIES_HOSTNAME
  echo "REMEMBER TO CLOSE THE TERMINAL AFTER THIS SESSION, OR CALLING source buildenv.bash AGAIN WHEN YOU'RE DONE"
  grunt quickServe
}

# Does debugging production still work?
function debugproduction() {
  #Try to debug staging
  export PROXY_TARGET_HOST='https://cad.onshape.com'
  unset HOST_PROPERTIES_PRIVATEIP
  unset HOST_PROPERTIES_HOSTNAME
  echo "REMEMBER TO CLOSE THE TERMINAL AFTER THIS SESSION, OR CALLING source buildenv.bash AGAIN WHEN YOU'RE DONE"
  grunt quickServe
}

function removeDiskImages() {
  rm -rf $HOME/build_tools/diskimage
}

function fixDiskImagesJS() {
  diskImageUmountAll
  rm $BUILD_TOOLS/diskimage/onshape-javascript_*
  source buildenv.bash
}


function importextractedfile() {
  if string.isemptyorblank "$1"
  then
    print_error "Please provide file path to restore."
    return 1
  fi
  local filePath="$1"
  local time1=$SECONDS
  waitforenterkey "If the file doesn't include std, make sure you've run 'mongoDropToProduction' and 'gradle runBtUpgrade' before this (press enter if yes, and Ctrl+C if you haven't)"
  # restoreDump "$filePath" --nodrop --remap=btadmin@onshape.com
  restoreDump "$filePath" --nodrop --remap=pisoni@onshape.com
  local time2=$SECONDS
  local duration=$(($time2-$time1))
  echo "Time taken in restore: $duration seconds"
  say "Document import complete"
  if ! general.inputyesorno "Do you want to open the document now?"
  then
    local documentId=$(echo "$filePath" | sed 's/.*new-\([^-]*\)-.*/\1/')
    if string.isemptyorblank "$documentId"
    then
      print_error "Could not find documentId from path. Looked for string between 'new-' and next '-'"
      return 1
    else
      local onshapePath="$(getdefaultonshapepath)/documents/$documentId"
      open "$onshapePath"
    fi
  fi
}

function runupgrade() {
  gradle runDocumentUpgrade -Donshape.upgrade.exitwhenfinished=true
}

function runretrieval() {
  waitforenterkey "Have you run setupforproductionretrieval before this? If yes, press Enter, else press Ctrl+C and do that first."

  if string.isemptyorblank $1
  then
    echo "A numeric Jenkins build id is required"
    return
  fi

  # If there's a second argument specified, take it as the documentidregex string
  # input to the retrieval service (which you should ideally pass without spaces,
  # as I haven't tested what will happen with spaces in these arguments :) )
  if string.isemptyorblank $2
  then
    gradle runProductionRetrieval -Donshape.productionretrieval.local=true -Donshape.productionretrieval.exitwhenfinished=true -Donshape.productionretrieval.jenkinsbuildid=$1
  else
    gradle runProductionRetrieval -Donshape.productionretrieval.local=true -Donshape.productionretrieval.exitwhenfinished=true -Donshape.productionretrieval.jenkinsbuildid=$1 -Donshape.productionretrieval.documentidregex=$2
  fi
}

function makelikeproduction() {
  #Make sure Docker is running, and mongo service is running as well
  mongoDumpDb #Note where it's created
  stopbelcad
  mongoDropAll
  mongoDropToProduction
  export SKIP_INTERNAL_MODULES=1
  waitforenterkey "Press enter if gradle runBtUpgrade is needed, else press Ctrl.+C to end"
  gradle runBtUpgrade
}


function cleanjars() {
  find "$HOME/stage/build/" -name *.jar -delete
}

function makelikeproductionwithbuild() {
  makelikeproduction
  buildgradleparallel # Then restore dump, and then it might need gradle runBtUpgrade again before running runupgrade
}

function openconfigpropertiesjson() {
  texteditor $REPO_NEWTON/project/web/WEB-INF/config/config-properties.json
}

function openupgradelogweb() {
  edit $upgradelogwebpath
}

function openbttimerlogweb() {
  edit $timerlogwebpath
}

function openbtserverweblog() {
  texteditor $btserverwebpath
}

function openbtservermodlog() {
  texteditor $btservermodpath
}

function opentimerlogweb() {
  texteditor $timerlogwebpath
}

function opentimerlogmod() {
  texteditor $timerlogmodpath
}

function cleanbtserverweblog() {
  system.cleanfilecontents "$btserverwebpath" "--silent"
}

function cleanbtservermodlog() {
 system.cleanfilecontents "$btservermodpath" "--silent"
}

function cleanlogs() {
  # These should not be needed and aren't even used in normal cases,
  # but sometimes our logs go into the logsDir_IS_UNDEFINED directory
  # for some reasons.
  system.cleanfilecontents "$undefinedtimerlogwebpath" "--silent"
  system.cleanfilecontents "$undefinedbtserverwebpath"
  system.cleanfilecontents "$undefinedbtservermodpath"

  cleanbtserverweblog
  cleanbtservermodlog
  system.cleanfilecontents "$timerlogwebpath" "--silent"
  system.cleanfilecontents "$timerlogmodpath" "--silent"
  system.cleanfilecontents "$upgradelogwebpath" "--silent"
}

function setupforproductionretrieval() {
  # First make your environment 'like' production (though that might not be necessary to just 'run' and debug the code)
  #makelikeproduction
  echo "setting SKIP_INTERNAL_MODULES to 1"
  export SKIP_INTERNAL_MODULES=1
  openconfigpropertiesjson
  echo "Change the defaultValue of productionretrieval.write-s3 from false to true in the opened config-properties.json"
  waitforenterkey "Press enter when done"
  echo "Build (gradle) manually now using buildgradleparallel"
  #buildgradleparallel
  #waitforenterkey "Press enter when done"
  echo "Import documents to upgrade."
  echo "call runupgrade to run document upgrade"
  #runupgrade
  #waitforenterkey "Press enter when upgrade has been done"
  echo "You can now see upgrade logs in $STAGE/ModelingSvc/logs/btserver.log"
  echo "Also, the upgrade data should be written to $STAGE/MockS3/onshape-myregion/test/operations/myenv/regen-data"
  #open "$STAGE/MockS3/onshape-us-east-1/test/operations/myenv/regen-data"
  echo "Finally, run the local production retrieval process by calling runretrieval"
  #runretrieval
}

function waitforenterkey() {
  read -p "$1"
}

function openmocks3cache() {
  local envNum=$(env.getnumber)
  local envString="myenv"
  if ! string.equals $envNum "0"
  then
    envString="myenv$envNum"
  fi

  open "$STAGE/MockS3/onshape-cache-us-west-2/test/cache/$envString/c/15"
}

function openbuildtools() {
  open $CURRENT_BUILD_TOOLS_PATH
}

function getbuildtoolsversion() {
  string.simplereplace $CURRENT_BUILD_TOOLS_PATH "$HOME/build_tools/build-tools/" ""
}

function runjunittest() {
    gradle safelyRunSpecificTests -Dtest=$1
}

function awsconfigure() {
  btAws configure --profile codebuild
}

function checkpmd() {
  gradle :java:pmd
}

function myprecommit() {
  # Remove this first line once yarn precommit starts catching
  # typescript errors again
  #npx tsc --noEmit --project $REPO_NEWTON/project/web/tsconfig.json
  checkTidy && checkpmd && (grunt checkJsCode)
}

function addstaticroutetojumpbox() {
  sudo route -n add 54.187.217.158/32 $1
}

function getnewbranchname() {
  local inputbranchname=$(string.tolower $1)
  local targetbranch=$(string.tolower $2)

  # Remove all lsb-release, lsb-master, -master, rel- etc. suffixes from the branch  name
  inputbranchname=$(string.simplereplace $inputbranchname "-lsb-*" "")
  inputbranchname=$(string.simplereplace $inputbranchname "-master" "")
  inputbranchname=$(string.simplereplace $inputbranchname "-release" "")
  inputbranchname=$(string.simplereplace $inputbranchname "-rel-[1-9]*" "")
  # Since we're creating a new branch, remove the 'merged'/'archived' words if there
  inputbranchname=$(string.simplereplace $inputbranchname "merged/" "")
  inputbranchname=$(string.simplereplace $inputbranchname "archived/" "")

  if ! (string.beginswith $inputbranchname "$USER/")
  then
    inputbranchname=$USER/$inputbranchname
  fi

  if string.isnotemptyorblank $targetbranch
  then
    targetbranch=$(string.simplereplace $targetbranch "/" "-")
    inputbranchname=$inputbranchname-$targetbranch
  fi

  echo $inputbranchname
}

function checkoutfrommaster() {
  ensurenewtondirectory
  git checkout master
  git pull
  git checkout -b $(getnewbranchname $1 "master")
  latestcreatedbranch=$(git.getcurrentbranch)
}

function checkoutfromrelease() {
  ensurenewtondirectory
  refreshcurrentreleasebranch #local refresh
  git checkout $CURRENT_RELEASE
  git pull
  git checkout -b $(getnewbranchname $1 $CURRENT_RELEASE)
  latestcreatedbranch=$(git.getcurrentbranch)
}

function checkoutfromlsbbranch() {
  if string.isemptyorblank $1
  then
    print_error "Please provide new branch name"
    return 1
  elif string.isemptyorblank $2
  then
    print_error "Please provide the base branch name"
    return 1
  else
    gitBranchLsb $(getnewbranchname $1 "lsb/$2") $2
  fi

  latestcreatedbranch=$(git.getcurrentbranch)
}

function checkoutfromlsbmaster() {
  ensurenewtondirectory
  checkoutfromlsbbranch "$1" "master" #lsb/ is eventually appended by gitBranchLsb
}

function checkoutfromlsbrelease() {
  ensurenewtondirectory
  refreshcurrentreleasebranch #local refresh
  checkoutfromlsbbranch "$1" "$CURRENT_RELEASE" #lsb/ is eventually appended by gitBranchLsb
}

function rebaselatest() {
  pulllatest "rebase"
}

# Unless otherwise specified, default branch for rbt is master
function pulllatest() {
  local branchname=$(git.getcurrentbranch)
  if string.equals $branchname "master" || string.equals "$branchname" "$CURRENT_RELEASE"
  then
    echo "Detected $branchname branch itself. Just doing a git pull"
    # Branch is master or latest release itself. Just do a git pull
    git pull
  elif git.branchislsbmasterbased
  then
    echo "Detected lsb/master based branch. Rebasing w.r.t. that"
    pulllatestbranch "$LSB_MASTER" $1 # Assuming $1 would be "rebase" when needed (e.g. called from rebaselatest), and empty otherwise
  elif git.branchislsbreleasebased
  then
    refreshcurrentreleasebranch
    echo "Detected lsb/rel-* based branch. Rebasing w.r.t. $LSB_CURRENT_RELEASE"

    if string.isnotemptyorblank "$LSB_CURRENT_RELEASE"
    then
        pulllatestbranch "$LSB_CURRENT_RELEASE" $1
    else
        echo "refreshing CURRENT_RELEASE and LSB_CURRENT_RELEASE failed. Please set them manually. Exiting now."
        return 1
    fi
  elif git.branchismasterbased || string.equals "$branchname" "master"
  then
    echo "Detected master based branch. Rebasing w.r.t. that"
    pulllatestbranch "master" $1
  elif git.branchisreleasebased || string.equals "$branchname" "$CURRENT_RELEASE"
  then
    echo "Detected rel-* based branch. Rebasing w.r.t. that"
    if string.isemptyorblank "$CURRENT_RELEASE"
    then
        refreshcurrentreleasebranch
    fi

    if string.isnotemptyorblank "$CURRENT_RELEASE"
    then
        pulllatestbranch "$CURRENT_RELEASE" $1
    else
        echo "refreshing CURRENT_RELEASE failed. Please set it manually. Exiting now."
        return 1
    fi
  else
    echo "Didn't detect standard (lsb/)master/release based branches, defaulting to master based rebase"
    pulllatestbranch "master" $1
  fi
}

function rebaselatestbranch() {
  pulllatestbranch $1 "rebase"
}

function pulllatestbranch() {
  if string.isemptyorblank $1
  then
    echo "Please give the branch name"
  else
    local argument=""
    if string.contains "$2" "rebase" || string.equals "$2" "-r"
    then
      argument="--rebase"
    fi

    echo "Calling pullmerge $1 $argument"
    pullmerge "$1" $argument
    if system.waslastcommandsuccessful
    then
      echo "$USER: pullmerge successful"
      return 0
    else
      echo "$USER: pullmerge failed"
      return 1 # failure
    fi
  fi
}

# rbt post and updates
function rbtpostfrombranch() {
  local sourcebranch="$1"
  if string.isemptyorblank $sourcebranch
  then
    echo "Please give the branch name w.r.t. which you want to create diff"
    return 1
  fi

  # Populate information for the 'Bugs' field on rbcommons page
  local bugNumberStr=""
  local bugNumber=$(git.getbugnumberfrombranch)
  if ! string.isemptyorblank $bugNumber
  then
    bugNumberStr="--bugs-closed $bugNumber"
  fi

  # Populate information for the 'Branch' field on rbcommons
  local masterVersion=$(getNewtonVersion)
  local suffix=""
  if string.isnotemptyorblank $masterVersion
  then
    suffix=" ($masterVersion)"
  fi

  # local branchStr="--branch \"master$suffix\"" #not working :|
  local branchStr="--branch master"
  if string.contains $sourcebranch "rel-"
  then
    branchStr="--branch $CURRENT_RELEASE"
  fi

  # To-Do : Handle --target-people <username,...> (reviewers)
  local reviewers=$(env.readvarfromdisk RBT_REVIEWERS)
  if ! string.isemptyorblank $reviewers
  then
    reviewers="--target-people ""$reviewers"
  fi

  echo "Calling rbt post --markdown -o $branchStr $bugNumberStr $reviewers $sourcebranch...HEAD"
  rbt post --markdown -o $branchStr $bugNumberStr $reviewers $sourcebranch...HEAD
}

# If a single or comma separated reviewer id is set (what you put in rbcommons reviewers list)
# it will be auto populated in the created review requests.
function setrbtreviewer() {
  local RBT_REVIEWERS="$1"

  env.writevartodisk RBT_REVIEWERS
}


# Unless otherwise specified, default branch for rbt is master
function rbtpost() {
  ensurenewtondirectory

  if git.hasUncommittedChanges
  then
    echo "There are uncommitted changes. Please fix before proceeding."
    return
  fi

  if git.branchislsbmasterbased
  then
    echo "Detected lsb/master based branch. Creating diff w.r.t. that"
    rbtpostfrombranch $LSB_MASTER
  elif git.branchislsbreleasebased
  then
    echo "Detected lsb/rel-* based branch. Creating diff w.r.t. that"
    rbtpostfrombranch $LSB_CURRENT_RELEASE
  elif git.branchismasterbased
  then
    echo "Detected lsb/master based branch. Creating diff w.r.t. that"
    rbtpostfrombranch "master"
  elif git.branchisreleasebased
  then
  echo "Detected rel-* based branch. Creating diff w.r.t. that"
    rbtpostfrombranch $CURRENT_RELEASE
  else
    echo "Didn't detect standard (lsb/)master/release based branches, defaulting to master based diff"
    rbtpostfrombranch "master"
  fi
}

function rbtupdatefrombranch() {
  if string.isemptyorblank $1
  then
    echo "Please give the branch name"
  elif string.isemptyorblank $2
  then
    reviewrequestid=$(rbt.getcurrentid $rbt_REVIEW_STATUS_ANY)
    if string.isemptyorblank $reviewrequestid
    then
      echo "Didn't find a matching review request for the branch, enter manually."
    else
      echo "Automatically found review request id: $reviewrequestid for current branch"
      rbtupdatefrombranch $1 $reviewrequestid
    fi
  else
    echo "Calling rbt post --markdown -o -u -r $2 $1...HEAD"
    rbt post --markdown -o -u -r $2 $1...HEAD
  fi
}

# Unless otherwise specified, default branch for rbt is master
function rbtupdate() {
  ensurenewtondirectory

  if git.hasUncommittedChanges
  then
    echo "There are uncommitted changes. Please fix before proceeding."
    return
  fi

  if git.branchislsbmasterbased
  then
    echo "Detected lsb/master based branch. Creating diff w.r.t. that"
    rbtupdatefrombranch $LSB_MASTER $@
  elif git.branchislsbreleasebased
  then
    echo "Detected lsb/rel-* based branch. Creating diff w.r.t. that"
    rbtupdatefrombranch $LSB_CURRENT_RELEASE $@
  elif git.branchismasterbased
  then
    echo "Detected lsb/master based branch. Creating diff w.r.t. that"
    rbtupdatefrombranch "master" $@
  elif git.branchisreleasebased
  then
  echo "Detected rel-* based branch. Creating diff w.r.t. that"
    rbtupdatefrombranch $CURRENT_RELEASE $@
  else
    echo "Didn't detect standard (lsb/)master/release based branches, defaulting to master based diff"
    rbtupdatefrombranch "master" $@
  fi
}

function rbtpostwithrebase() {
  rebaselatest
  if system.waslastcommandsuccessful
  then
    rbtpost
  else
    echo "Not calling rbtpost as rebase was not successful."
  fi
}

function rbtupdatewithrebase() {
  rebaselatest
  if system.waslastcommandsuccessful
  then
    rbtupdate
  else
    echo "Not calling rbtupdate as rebase was not successful."
  fi
}


function setupjumpboxcertificates() {
  scp $USERNAME@jumpbox-primary.dev.onshape.com:$USER.key /tmp
  scp $USERNAME@jumpbox-primary.dev.onshape.com:$USER.crt /tmp
  scp $USERNAME@jumpbox-primary.dev.onshape.com:ca.crt /tmp
  scp $USERNAME@jumpbox-primary.dev.onshape.com:tls-auth.key /tmp
}



function getNewtonVersion() {
  local newtonVersion=$(getBuildProp NEWTON_VERSION)
  if string.isnotemptyorblank $newtonVersion
  then
    echo "rel-$newtonVersion"
  else
    echo ""
  fi
}

function monitorenv() {
  export MONITORING_ENV="true"
  local wasWorkingBefore="false"

  while env.check; do
    echo ""
    echo $(system.getcurrentdate)
    wasWorkingBefore="true"
    sleep 5
  done

  unset MONITORING_ENV

  if string.equals $wasWorkingBefore "true"
  then
    beep;beep
    local message="Something has crashed in Environment $(env.getnumber)"
    echo $message
    say $message
    return 1
  else
    echo "Environment check failed."
    return 1
  fi
}


function beep() {
  tput bel
}

# Only works on mac by default (No linux support)
function playfinishsound() {
  beep;beep
  if string.isemptyorblank $1
  then
    say "Build Complete"
  else
    say "$1"
  fi
}

function isJSBuildActive() {
  ! string.equals $(getBuildProp "SKIP_JSLIB") "1"
}

function buildgradleparallel() {
  # Not being in newton directory has caused problems too many times while building
  ensurenewtondirectory

  if isJSBuildActive && isquickserverunning
  then
    # Stop webpack server if already running
    # because the build process would start a few
    # of its own, taking a LOT of your RAM.
    fstopquickserve
  fi

  # Similarly, our build tools don't figure out if docker itself is not running
  if ! docker.isrunning
  then
    startServices # Will ensure docker and services run
  fi

  echo "Calling gradle --parallel $@"
  # Start the actual build now.
  gradle --parallel "$@"

  if system.waslastcommandsuccessful
  then
    playfinishsound "Build successful"
    # If the build was successful, and a handler is defined, call it now.
    if system.functionexists onsuccessfulbuild
    then
      onsuccessfulbuild & >/dev/null # Fire the onsuccessfulbuild function async.
    fi
    return 0
  else
    playfinishsound "Build failed"
    return 1
  fi
}

# There's no reason to keep merged branches
# but we can keep for a few days just for reference purposes
function markbranchmerged() {
  local branchname=$1
  if string.isemptyorblank $branchname
  then
    branchname=$(git.getcurrentbranch)
  fi
  local curdatetime=$(system.getcurrentdate)
  git.renamebranch $branchname merged/$branchname/$curdatetime
}

function markbranchreopened() {
  local oldbranchname=$1
  if string.isemptyorblank $branchname
  then
    oldbranchname=$(git.getcurrentbranch)
  fi

  local newbranchname=$(string.simplereplace $oldbranchname "merged/" "")
  local bugNumber=$(git.getbugnumberfrombranch $oldbranchname)
  bugNumber=$(string.tolower "$bugNumber")
  newbranchname=$(string.simplereplace $newbranchname "$bugNumber/" "$bugNumber/reopened/")
  git.renamebranch $oldbranchname $newbranchname
}

function markbrancharchived() {
  local branchname=$1
  if string.isemptyorblank $branchname
  then
    branchname=$(git.getcurrentbranch)
  fi
  git.renamebranch $branchname archived/$branchname
}

function createlsbreleasebranchfromlsbmastertopchange() {
  if ! git.branchislsbmasterbased
  then
    echo "It's not an lsb/master based branch. Please check the branch name again."
    return
  fi

  local topSHAId=$(git.getlatestcommitid)
  local currentbranch=$(git.getcurrentbranch)
  checkoutfromlsbrelease $(getnewbranchname $currentbranch $LSB_CURRENT_RELEASE)
  git cherry-pick $topSHAId
}

function createrevertmasterbranchfrombranchtopchange() {
  local topSHAId=$(git.getlatestcommitid)
  local currentbranch=$(git.getcurrentbranch)
  checkoutfrommaster "$currentbranch-revert"
  git revert -m 1 $topSHAId
}

function createlsbmasterbranchfromlsbreleasetopchange() {
  if ! git.branchislsbreleasebased
  then
    echo "It's not an lsb/release based branch. Please check the branch name again."
    return
  fi
  local topSHAId=$(git.getlatestcommitid)
  local currentbranch=$(git.getcurrentbranch)
  checkoutfromlsbmaster $(getnewbranchname $currentbranch $LSB_MASTER)
  git cherry-pick $topSHAId
}

# Merge a branch to master following the complete process outlined in Onshape's Software Release Process
# (https://belmonttechinc.atlassian.net/wiki/spaces/DEV/pages/10387559/Software+Release+Process)
# Syntax: Call `mergetomaster [review-request-id]` - review-request-id is optional. If you don't pass
# it, it will automatically find the *approved* RBCommons Review request with the same branch name.
# If it's not approved it won't be merged. It works as expected as long as the branch was originally
# created by checkoutfromlsbmaster or checkoutfrommaster - which merely adds a "-lsb-master" or "-master"
# at the end of the branch to denote the original branch it was based off of.
function mergetomaster() {
  ensurenewtondirectory
  local reviewrequestid="$1"

  if git.hasUncommittedChanges
  then
    echo "There are uncommitted changes. Please fix before merging to master"
    return 1
  fi

  if git.isoneoftheofficialbranches
  then
    echo "Wrong branch. You should call it on your feature branch and not on one of the official branches"
    return 1
  fi

  if ! git.branchislsbmasterbased && ! git.branchismasterbased
  then
    echo "Branch is not lsb/master or master based (Was it created using checkoutfrommaster or checkoutfromlsbmaster?). It is checked by whether the branch name ends with "-master" or "-lsb-master"). Please fix and try again"
    return 1
  fi

  # Check if a specific rbcommons review request id is given
  # Search for an approved request for the current git branch if not.
  if string.isemptyorblank "$reviewrequestid" && ! isreverting # If reverting we don't need to pull review request id
  then
    reviewrequestid=$(rbt.getcurrentid $rbt_REVIEW_STATUS_APPROVED)
    if string.isemptyorblank $reviewrequestid || ! string.isnumber $reviewrequestid
    then
      echo "Didn't find an approved review request for the branch, enter manually."
      return 1
    else
      echo "Automatically found approved review request id: $reviewrequestid for current branch, using that for merging."
    fi
  fi

  # Start the merging process now.
  local currentbranch=$(git.getcurrentbranch)

  if string.isemptyorblank $(git.getbugnumberfrombranch)
  then
    # No bug number found in the branch name. Merge without a bug number if the user agrees.
    if user_agrees_to "Branch name does not contain a bug number. Do you want to merge with '--no-resolve'?"
    then
      echo "Sure, will mergepush with --no-resolve"
      setnoresolve
    else
      echo "No bug number found in the branch name. Please ensure the branch name is of the form <username>/bel-xxxxxx[/optional-description]-[lsb/master/lsb/rel-*.***] and run again. Or, you could just create the branch name using checkoutfromlsbmaster or checkoutfromlsbrelease"
      return 1
    fi
  fi

  # Actually check for no-resolve here
    local noresolvestring=""
    if getisnotresolving
    then
      noresolvestring="--no-resolve"
    fi

    local ignorebuildfarmstring=""
    if getignorebuildfarmforrbcommons
    then
      ignorebuildfarmstring="--no-build-farm"
    fi

  # Step 1: Rebase latest master branch (regardless of whether it was an lsb/master based branch or just master based)
  rebaselatestbranch "master"
  if ! system.waslastcommandsuccessful
  then
    echo "Rebase didn't succeed. Please manually rebase/pull latest master branch and try again."
    return 1
  fi

  waitforenterkey "Press enter if rebase is successful to continue to merge to master"

  # Step 2: Checkout master
  git checkout master
  if ! system.waslastcommandsuccessful
  then
    echo "git checkout failed, did not merge to master"
    return 1
  fi

  # If we are reverting this branch from master (this branch itself was
  # previously merged, and we are calling `revertbranchfrommaster` function)
  # then we don't need a review request id
  if isreverting
  then
    echo "Calling  mergepush $currentbranch --no-review -m \"$reviewrequestid\""
    mergepush "$currentbranch" --no-review -m "$reviewrequestid" # In this case the first argument is the revert comment.
    if system.waslastcommandsuccessful
    then
      setnotreverting
    fi
  else
    # Step 3: Call mergepush
    local cmd="mergepush $currentbranch -r $reviewrequestid $noresolvestring $ignorebuildfarmstring"
    echo "Calling $cmd"
    mergepush $currentbranch -r $reviewrequestid $noresolvestring $ignorebuildfarmstring
    if system.waslastcommandsuccessful
    then
      git checkout $currentbranch
      # This is not really needed, but rename the current branch as 'merged' to keep for
      # a few days in case you need to revert it. It can be deleted later.
      markbranchmerged $currentbranch
      unsetnoresolve
      unsetignorebuildfarmforrbcommons
    else
      echo "mergepush was not succecsful, please call it again on the master."
      return 1
    fi
  fi
}

# Revert a branch you merged to master. You should be on the branch
# to revert for calling this.
# Please make sure all the changes you did are in a single top
# commit in this branch (Squash changes first if that's not the case).
# The revert branch would be created by cherry picking the top-most commit
# in that branch.
function revertbranchfrommaster() {
  local revertcomment="$1"
  if string.isemptyorblank "$revertcomment"
  then
    echo "Please enter a revert comment in quotes as input to this command (try again)."
    return
  fi

  ensurenewtondirectory

  if git.hasUncommittedChanges
  then
    echo "There are uncommitted changes. Please fix before merging to master"
    return
  fi

  if git.isoneoftheofficialbranches
  then
    echo "Wrong branch. You should call it on your feature branch and not on one of the official branches"
    return
  fi

  if ! git.branchislsbmasterbased && ! git.branchismasterbased
  then
    echo "Branch is not lsb/master or master based. Please check and try again"
    return
  fi

  waitforenterkey "Press enter to proceed only if there are no FeatureScript changes. If there are, press Ctrl+C and do it manually."

  git log -n 3
  waitforenterkey "Press enter if all of your changes are in one top commit, and ready to create the revert branch from it (Otherwise press Ctrl+C and try again after squashing them to one change, or do manually)."
  createrevertmasterbranchfrombranchtopchange

  if ! system.waslastcommandsuccessful
  then
    echo "Revert has merge problems. Resolve those, and then merge the branch to master using mergetomaster"
    return
  fi

  waitforenterkey "Press enter if the revert commit was successful, else press Ctrl+C and mergetomaster later."
  setreverting
  mergetomaster "$revertcomment"
}

function setreverting() {
  export REVERTING_CHANGES=1
}

function isreverting() {
  string.isnotemptyorblank $REVERTING_CHANGES
}

function setnotreverting() {
  unset REVERTING_CHANGES
}

function setnoresolve() {
  export RBCOMMONS_NO_RESOLVE=1
}

function unsetnoresolve() {
  unset RBCOMMONS_NO_RESOLVE
}

function getisnotresolving() {
  string.isnotemptyorblank $RBCOMMONS_NO_RESOLVE
}

function setignorebuildfarmforrbcommons() {
  export IGNORE_BUILD_FARM_FOR_RBCOMMONS=1
}

function getignorebuildfarmforrbcommons() {
  string.isnotemptyorblank $IGNORE_BUILD_FARM_FOR_RBCOMMONS
}

function unsetignorebuildfarmforrbcommons() {
  unset IGNORE_BUILD_FARM_FOR_RBCOMMONS
}

function mergetoreleasethenmaster() {
  ensurenewtondirectory
  local reviewrequestid=$1

  if git.hasUncommittedChanges
  then
    echo "There are uncommitted changes. Please fix before merging to release"
    return 1
  fi

  # Check if accidentally calling this script on (lsb/) master/rel-* itself
  if git.isoneoftheofficialbranches
  then
    echo "Wrong branch. You should call it on your feature branch and not on one of the official branches"
    return 1
  fi

  local currentbranch=$(git.getcurrentbranch)

  if ! (string.endswith $currentbranch "-rel-[0-9].[0-9]*")
  then
    if git.branchislsbmasterbased
    then
      # Try automatically creating lsb/release based branch of it with the top commit.
      git log -n 3
      waitforenterkey "lsb/master based branch found. Press enter if all of your changes are in one top commit, and ready to create lsb/release branch off it (Otherwise press Ctrl+C and try again later)."
      createlsbreleasebranchfromlsbmastertopchange
      waitforenterkey "Press enter if the lsb/release branch creation and cherry picking from source branch commit was successful, otherwise either resolve merge issues in another tab before pressing enter here, or press Ctrl+C to terminate operation and do it all manually."
      currentbranch=$(git.getcurrentbranch)
      echo "Created branch $currentbranch from the lsb/master based branch with the same commit"
    else
      echo "Branch does not end with a -rel-x.y* pattern. Please check and run manually"
      return 1
    fi
  fi

  if string.isemptyorblank $reviewrequestid
  then
    reviewrequestid=$(rbt.getcurrentid $rbt_REVIEW_STATUS_APPROVED)
    if string.isemptyorblank $reviewrequestid || ! string.isnumber $reviewrequestid
    then
      echo "Didn't find an approved review request for the branch, enter manually."
      return 1
    else
      echo "Automatically found approved review request id: $reviewrequestid for current branch, merging with the same"
    fi
  fi

  # Fetch the latest release branch from the server
  refreshcurrentreleasebranch --remote
  waitforenterkey "Will merge to release branch : $CURRENT_RELEASE. Press enter if that's correct, else press Ctrl+C to terminate this function, call 'export CURRENT_RELEASE=rel-<correct-version>' without single quotes and call this function again."

  local ignorebuildfarmstring=""
  if getignorebuildfarmforrbcommons
  then
    ignorebuildfarmstring="--no-build-farm"
  fi

  # Merge to release first
  # Step 1: Rebase latest release branch.
  rebaselatestbranch $CURRENT_RELEASE

  if ! system.waslastcommandsuccessful
  then
      echo "Rebase didn't succeed. Please manually rebase/pull latest master branch and try again."
      return 1
  fi

  waitforenterkey "Press enter if and when rebase is successful to continue to merge to release, otherwise press Ctrl+C and do it manually"

  # Step 2: Checkout latest release
  git checkout $CURRENT_RELEASE

  # Step 3: Call mergepush to release.
  echo "Calling mergepush $currentbranch -r $reviewrequestid $ignorebuildfarmstring"
  mergepush $currentbranch -r $reviewrequestid $ignorebuildfarmstring

  if ! system.waslastcommandsuccessful
  then
      echo "mergepush didn't succeed. Please manually resolve the problem and try again."
      return 1
  fi

  # Merge changes back to master
  waitforenterkey "Merging changes to master now, press enter when ready"
  checkoutfrommaster $currentbranch # Will create new branch from master taking name from $currentbranch

  # Rename the last branch before reassigning the variable to the current one.
  markbranchmerged $currentbranch

  currentbranch=$(git.getcurrentbranch)

  # Step 4: Merge latest release into current branch.
  git merge $CURRENT_RELEASE

  if ! system.waslastcommandsuccessful
  then
      waitforenterkey "Merging release into master was NOT successful. Please resolve merge issues in another tab and then press enter here to continue, or press Ctrl+C and carry remaining steps manually."
      waitforenterkey "Just double checking. You are sure the merge issues are resolved in another tab? Press enter if yes, or Ctrl+C to quit from here and do rest of the steps manually."
  fi

  # Step 5: Validate that only your commits are included. If you see more than your changes here, wait for other authors to push  theirs, do pullmerge master after that or ask them if it is OK to push the changes to master.
  git log --format="%an: %s" master..$currentbranch
  waitforenterkey "Press enter if you see only your commits above, otherwise press Ctrl+C and do it manually"

  # Step 6: Checkout master
  git checkout master

  # Step 7: Call mergepush with master this time.
  mergepush $currentbranch -r $reviewrequestid --no-resolve $ignorebuildfarmstring # don't resolve the bug again, so fixed-in hash keeps pointing to the rel branch

  # Step 8: Unset the IGNORE_BUILD_FARM_FOR_RBCOMMONS env variable
  unsetignorebuildfarmforrbcommons

  # Just like we did in `mergetomaster`, these steps are not required but we do it in case we would need to revert them for a few days.
  git checkout $currentbranch
  markbranchmerged $currentbranch
}


function quickserve() {
  ensurenewtondirectory
  grunt quickServe
}


function buildall() {
  cd $REPO_NEWTON
  buildgradleparallel $@
}

function buildjavaonly() {
    export SKIP_DRAWING=1
    export SKIP_CPP=1
    export SKIP_JSLIB=1
    buildgradleparallel $@
    local returnvalue=$?
    unset SKIP_CPP
    unset SKIP_JSLIB
    unset SKIP_DRAWING

    return $returnvalue
}

function buildjsonly() {
    export SKIP_DRAWING=1
    export SKIP_CPP=1
    export SKIP_JAVA=1
    # In some cases you might have made a change to the serializable
    # classes and would need to generate new serializable code that's
    # applicable to JS code, but that's still Java code and it's understood
    #  that for that you'd either buildjava, OR generate serializables separately
    # using the `genser` command
    export SKIP_SERIALIZABLES=1
    buildgradleparallel -x runBtUpgrade $@
    local returnvalue=$?
    unset SKIP_CPP
    unset SKIP_JAVA
    unset SKIP_DRAWING
    unset SKIP_SERIALIZABLES
    return $returnvalue
}

function buildcpponly() {
    export SKIP_DRAWING=1
    export SKIP_JSLIB=1
    export SKIP_JAVA=1
    export SKIP_SERIALIZABLES=1
    buildgradleparallel $@
    local returnvalue=$?
    unset SKIP_JSLIB
    unset SKIP_JAVA
    unset SKIP_DRAWING
    unset SKIP_SERIALIZABLES
    return $returnvalue
}

function buildjavaandjsonly() {
    export SKIP_DRAWING=1
    export SKIP_CPP=1
    buildgradleparallel $@
    local returnvalue=$?
    unset SKIP_CPP
    unset SKIP_DRAWING
    return $returnvalue
}

function grdlbuildjavaandjsonly() {
  ensurenewtondirectory

  if ! docker.isrunning
  then
    startServices # Will ensure docker and services run
  fi

  grdlu gen java js $@ --parallel #Download binaries for CPP
  if system.waslastcommandsuccessful
  then
    playfinishsound "Build successful"
    # If the build was successful, and a handler is defined, call it now.
    if system.functionexists onsuccessfulbuild
    then
      onsuccessfulbuild & >/dev/null # Fire the onsuccessfulbuild function async.
    fi
    return 0
  else
    playfinishsound "Build failed"
    return 1
  fi
}


# Pass jira number, or leave blank for picking
# bug number from the branch name.
function openbug() {
  local bugNumber="$1"
  if string.isemptyorblank "$bugNumber"
  then
    # Assume we're trying to open the bug number contained in the branch
    bugNumber=$(git.getbugnumberfrombranch)
    if string.isemptyorblank "$bugNumber"
    then
      echo "Bug number not provided, and can't find one from the branch name."
      return
    fi
  fi

  bugNumber=$(string.toupper $bugNumber)
  if string.isnumber $bugNumber
  then
    # Take BEL by default.
    bugNumber="BEL-$bugNumber"
  fi

  open "https://belmonttechinc.atlassian.net/browse/$bugNumber"
}

function openbugfolder() {
  local bugNumber="$1"
  if string.isemptyorblank "$bugNumber"
  then
    # Assume we're trying to open the bug number contained in the branch
    bugNumber=$(git.getbugnumberfrombranch)
    if string.isemptyorblank "$bugNumber"
    then
      echo "Bug number not provided, and can't find one from the branch name."
      return
    fi
  fi

  bugNumber=$(string.simplereplace $(string.tolower $bugNumber) "bel-" "")
  bugNumber="BEL-$bugNumber"
  local bugsFolder=""
  if system.direxists "$HOME/Bugs"
  then
    bugsFolder="$HOME/Bugs"
  elif system.direxists "$HOME/Library/CloudStorage/OneDrive-PTC"
  then
    bugsFolder="$HOME/Library/CloudStorage/OneDrive-PTC/Documents/Bugs"
    system.createdirifdoesnotexist "$bugsFolder"
    # Create a symbolic link for this bug folder to the $HOME directory
    # for easy access later
    system.createsymboliclinkfromto "$bugsFolder" "$HOME/Bugs"
  fi

  system.createdirifdoesnotexist "$bugsFolder/$bugNumber"

  # Do a success check
  if ! system.direxists "$bugsFolder/$bugNumber"
  then
    print_error "Cannot create bug folder. Please create a 'Bugs' folder in $HOME, check write permissions and try again"
    return 1
  fi

  open "$bugsFolder/$bugNumber"
}

function getdefaultonshapepath() {
  local portString=""
  if isquickserverunning
  then
    portString=":$(getquickserveport)"
  fi

  if string.equals "$(env.getnumber)" "0"
  then
      echo "https://localhost.onshape.io$portString/"
  else
      echo "https://multienv$(env.getnumber).onshape.io$portString/"
  fi
}

function playtest() {
  # other flags:
  play $1 --verbose --flags=fastFail --target="$(getdefaultonshapepath)"
}

function pushtos3() {
  # Put a timestamp to the branch name and remove hyphen after bel from branch name
  # as otherwise kibana logs show the branch name only as "bel" and nothing else
  local originalbranchname=$(git.getcurrentbranch)
  local currentdatetime=$(system.getcurrentdate "_")
  currentdatetime=$(string.concatenate "$currentdatetime" "_")

  # Change bel-xxxxxx to bel_xxxxxx
  # sed syntax : "s,search_string,replace_string,regex_flags" (most other characters allowed as separator instead of ,)
  local newbranchname=$(echo $originalbranchname | sed -En "s,bel-([[:digit:]]+),bel_\1_$currentdatetime,p")
  # Change just a couple of hyphens to underscore for more info of the branch name to show up in elastic search
  newbranchname=$(string.replacefirstoccurrence $newbranchname '-' '_')
  newbranchname=$(string.replacefirstoccurrence $newbranchname '-' '_')
  #echo $originalbranchname
  #echo $newbranchname
  git.renamecurrentbranch $newbranchname
  pushToBuildFarm @promote-to-s3-test
  # After it's done, change the branch name back to original
  git.renamecurrentbranch $originalbranchname
}

# Function for visualizing timer.log times. Call this followed by opening
# localhost:8088 page in the browser. Visit https://github.com/onshape/timerdisplay
# for more details
function runTimerDisplay() {
  cd $HOME/repos/timerdisplay
  sleep 5 && open "http://localhost:8088" & # Delay launch the webpage :).
  ./server.js -p 8088 $STAGE/WebSvc/logs/timer.log --debug
}

# Remove from work (Better suited for personal profile)?
# Quickly create or update a dummy branch that's based on latest
# lsb/master. For those non-ideal times you need lsb/master as a branch
# and not as a tag.
function updatedummylsbmaster() {
  local checkoutPreviousBranch="$1"
  if ! string.equals $checkoutPreviousBranch "true" && ! string.equals $checkoutPreviousBranch "false"
  then
    checkoutPreviousBranch="true"
  fi

  # Store current branch
  local currentbranch=$(git.getcurrentbranch)
  local dummybranchname=$(getnewbranchname "dummy" "lsb/master")
  if git.localbranchexists $dummybranchname
  then
      if ! string.equals $currentbranch $dummybranchname
      then
        git checkout "$dummybranchname"
      fi
      pulllatest
  else
    echo "Updating $dummybranchname with latest lsb/master"
    checkoutfromlsbmaster "dummy"
  fi

  if ! string.equals $currentbranch $dummybranchname && string.equals $checkoutPreviousBranch "true"
  then
    echo "Checking out previous branch again"
    git checkout $currentbranch
  fi
}

function updateandcheckoutdummylsbmaster() {
  updatedummylsbmaster "false"
}

function updatedummylsbrelease() {
  local checkoutPreviousBranch="$1"
  if ! string.equals $checkoutPreviousBranch "true" && ! string.equals $checkoutPreviousBranch "false"
  then
    checkoutPreviousBranch="true"
  fi

  # Store current branch
  local currentbranch=$(git.getcurrentbranch)
  local dummybranchname=$(getnewbranchname "dummy" "$LSB_CURRENT_RELEASE")
  if git.localbranchexists $dummybranchname
  then
      if ! string.equals $currentbranch $dummybranchname
      then
        git checkout "$dummybranchname"
      fi
      pulllatest
  else
    echo "Updating $dummybranchname with latest lsb/release"
    checkoutfromlsbrelease "dummy"
  fi

  if ! string.equals $currentbranch $dummybranchname && string.equals $checkoutPreviousBranch "true"
  then
    echo "Checking out previous branch again"
    git checkout $currentbranch
  fi
}

function updateandcheckoutdummylsbrelease() {
  updatedummylsbrelease "false"
}

function cleaneverythingthatcanbecleaned() {
  if ! general.inputyesorno "This is a really, really nuclear solution. Are you sure you want to go with it" "caution"
  then
    return 0
  fi

  if ! general.inputyesorno "Ok, one more time. If you have to clean everything that is there to clean, probably fetching a new newton env might be better. Still sure want to clean everything that can be cleaned for this env" "caution"
  then
    return 0
  fi

  echo "Ok, here we go."
  ensurenewtondirectory

  echo "Stopping servers and services"
  stopservers
  stopallservices

  echo "mongoDropAll"
  mongoDropAll

  echo "mongoDropToProduction"
  mongoDropToProduction


  echo "Cleaning logs"
  cleanlogs

  echo "cleanEverything"
  cleanEverything

  echo "Removing $STAGE"
  rm -rf "$STAGE"

  echo "cleanMockS3"
    cleanMockS3

  if general.inputyesorno "Prune mongodb volumes"
  then
    echo "Pruning mongodb volumes"
    docker volume prune -af
  fi

  if general.inputyesorno "Remove angular cache"
  then
    echo "Removing .angular/cache"
    rm -rf ".angular/cache"
  fi

  if general.inputyesorno "Clean gradle cache"
  then
    echo "Removing ~/.gradle"
    rm -rf "~/.gradle"
  fi

  if general.inputyesorno "Clean build_tools"
    then
      echo "Removing ~/build_toools"
      rm -rf "~/build_toools"
    fi
}

# Change the timezone in the btserver.log etc. logs on the machine
# from UTC to Indian Standard Time
function changelogstimezonetoist() {
  locate "$STAGE/*logback.xml" | xargs sed -i '' 's/ISO8601, UTC/ISO8601, Asia\/Kolkata/g'
}

function openpatchesforbranch() {
  local bugNumber=$(git.getbugnumberfrombranch)
  open $(system.getdirectoryfrompath $(git.getpatchfilepath))
}

alias bfnodestop='bf job rm'
alias bfjobremove='bfnodestop'
alias bsserverpath="$STAGE/BSServer/bin/BSServer"
alias checknecessaryservices='checkessentialservices'
alias checkJsCode='grunt checkJsCode'
alias checkjs='grunt eslint:javascript'
alias checkts='grunt eslint:typescript'
# alias clion="open -a $HOME/Applications/JetBrains\ Toolbox/CLion.app"
alias cppbuild='buildcpponly'
alias droptoproduction='mongoDropToProduction'
alias eclipse='open -a /Applications/Eclipse.app'
alias eslintfix='grunt eslint:fix'
alias fixgruntnotfound='fixDiskImagesJS'
alias fixjs='grunt eslint:fix'
alias fixts='grunt eslint:fix'
alias fixlocalization='grunt xgettext --fix'
alias localizationfix='fixlocalization'
alias fixpo='fixlocalization'
alias killallbsservers='killbsservers'
alias languagefix='fixlocalization'
alias fixtranslation='fixlocalization'
alias translationfix='fixlocalization'
alias generateserializables='grunt generateSerializables'
alias genser='grunt generateSerializables'
alias gitlistskipignoredfiles='git ls-files -v . | grep ^S'
alias gruntQuickServe='grunt quickServe'
alias gruntserveonlan='setserveonlan'
alias inteli='intellij'
alias intellij='idea' #Jetbrains Toolbox generates the script 'idea' for version dependent IntelliJ IDEA
alias jira='openbug'
alias openjira='jira'
alias javabuild='buildjavaonly'
alias jsbuild='buildjsonly'
alias jumpboxaddstaticroute='addstaticroutetojumpbox'
alias jumpboxnetstat='netstat -rn | grep 52.210.113.201'
alias jumpboxssh='sshjumpbox'
alias listbsservers='getbsservers'
alias stopbsservers='killbsservers'
alias localprecommit='yarn precommit'
alias lsbreleasecheckout='checkoutfromlsbrelease'
# alias mergelatestmaster='pullmerge master'
alias mongodump='mongoDump'
alias mongobackup='mongoDump'
alias mongorestore='mongoRestore'
alias backupmongo='mongoDump'
alias restoremongo='mongoRestore'
alias gonewton='cd $REPO_NEWTON'
alias cdnewton='cd $REPO_NEWTON'
alias newtondir='cd $REPO_NEWTON'
alias kibanatools='cd $DEV_TOOLS/kibanaTools'
alias devtools='cd $DEV_TOOLS'
alias pofix='fixpo'
alias prepeclipse='gradle prepEclipse'
alias prepclion='gradle :cpp:prepCLion --parallel'
alias protractortest='ptortest'
alias runprotractortest='ptortest'
alias runptortest='ptortest'
# alias pullmaster='pullmerge master'
# alias pullmergemaster='pullmerge master'
alias pushtobuild='pushToBuildFarm @precommit @uitest @mocha'
alias ptortest='playtest'
# alias rebasemaster='pullmerge master --rebase'
alias serial='grunt generateSerializables'
alias serialize='grunt generateSerializables'
alias serveonlan='setserveonlan'
alias setisreverting='setreverting'
alias setdebugdrawings='setdebuggingdrawings'
alias sshjumpbox="ssh -X $USER@jumpbox-primary.dev.onshape.com"
alias startquickserve='quickserve'
alias staging='cd $STAGE'
alias starttimerdisplay='runTimerDisplay'
alias startallservers='startservers'
alias restartServices='stopallservices;startServices'
alias startfrontend='grunt quickServe'
alias timerdisplay='runTimerDisplay'
alias updaterbt='rbtupdate'
alias xcode='open -a Xcode.app $STAGE/build/cppServer/DebugXcodeCCache/BTcppServer.xcodeproj/'
alias web='webstorm'
alias webs='webstorm'
alias storm='webstorm'
alias productionretrievalconfigfile='$STAGE/ModelingSvc/webapps/root/WEB-INF/config/applicationContext.xml'
alias openbtserver='openbtserverweblog'
alias isbelcadrunning='isonshapeserverrunning'
alias opentimerlog='opentimerlogweb'
alias setnobuildfarm='setignorebuildfarmforrbcommons'
