#!/bin/bash

#include guard
if isFunctionDefined "git.defined" && ! isEnvVariableDefined "FORCE_IMPORT_UTILITY"
then
  return 0
fi

function git.defined() {
  return 0
}

export GIT_SKIP_TREE_FILES_LIST=~/.git-skipped-worktree-files
export GIT_PATCH_DIR="$HOME/patches"
export GIT_FILES_WITH_FOLDER_STRUCTURE_DIR="$HOME/patches/files_with_folder_structure"

## Ignore
export globalgitignorefile=$HOME/.gitignore
export globalgitconfigfile=$HOME/.gitconfig


# Import utility modules
importutility string
importutility system
importutility general

function __ensurepatchdirexists() {
  if ! system.direxists $GIT_PATCH_DIR
  then
    mkdir $GIT_PATCH_DIR
  fi
}

function git.renamebranch() {
	git branch -m $1 $2
}

function git.renamecurrentbranch() {
	git branch -m $1
}

function git.getcurrentbranch() {
  local currentbranch=$(git branch | sed -n -e 's/^\* \(.*\)/\1/p')
  echo $currentbranch
}

function git.hasUncommittedChanges() {
	[ -n "$(git status --porcelain)" ]
}

function git.getlatestcommitid() {
	local latestSHAId=$(git rev-parse HEAD | cut -c 1-8)
	echo $latestSHAId
}

function git.isoneoftheofficialbranches() {
  local currentbranch=$(git.getcurrentbranch)
  string.equals $currentbranch "master" || string.equals $currentbranch $CURRENT_RELEASE || string.equals $currentbranch $LSB_MASTER || string.equals $currentbranch $LSB_CURRENT_RELEASE
}

function git.branchislsbreleasebased() {
	local currentbranch=$(git.getcurrentbranch)
	string.endswith $currentbranch "-lsb-rel-[0-9].[0-9]*"
}

function git.branchislsbmasterbased() {
	local currentbranch=$(git.getcurrentbranch)
	#echo $currentbranch
	string.endswith $currentbranch "-lsb-master"
}


function git.branchisreleasebased() {
	local currentbranch=$(git.getcurrentbranch)
	! git.branchislsbreleasebased && string.endswith $currentbranch "-rel-[0-9].[0-9]*"
}

function git.branchismasterbased() {
	local currentbranch=$(git.getcurrentbranch)
	! git.branchislsbmasterbased && string.endswith $currentbranch "-master"
}

# Give the full file path for the _tracked_ file you want to ignore
function git.skipworktree() {
  git update-index --skip-worktree "$1"
  system.createfileifdoesnotexist $GIT_SKIP_TREE_FILES_LIST
  echo "$1">>$GIT_SKIP_TREE_FILES_LIST
}

function git.unskipworktree() {
  git update-index --no-skip-worktree $1
  if system.ismacos
  then
    # Seems this empty backup is required.
    sed -i '' "s|$1||g" $GIT_SKIP_TREE_FILES_LIST
  else
    sed -i "s|$1||g" $GIT_SKIP_TREE_FILES_LIST
  fi
}

function git.openskipworktreefile() {
  edit $GIT_SKIP_TREE_FILES_LIST
}

# ToDo : Refactor the common code out of the below two functions
function git.backupbranch() {
  local additionalNotes=""
  if string.isnotemptyorblank $1
  then
    # Replace spaces with hyphens if there's a comment to
    # add with the backup branch name and prepend a slash.
    additionalNotes=$(string.simplereplace "/$1" " " "-")
  fi

  local currentbranch=$(git.getcurrentbranch)
  local newbranch=""
  local searchstring=$USER
  local curdate=$(system.getcurrentdate)

  if string.contains $currentbranch $searchstring
  then
    local replacestring=backup/$USER
    newbranch="${currentbranch/$searchstring/$replacestring}$additionalNotes/$curdate"
  else
    newbranch="backup/$currentbranch$additionalNotes/$curdate"
  fi

  # create new backup branch
  git checkout -b $newbranch
  # go back to our branch
  git checkout $currentbranch
}

# Backup the current branch but mark that as 'starred', more important
# than the usual backups
function git.starbackupbranch() {
  currentbranch=$(git.getcurrentbranch)
  searchstring=$USER
  replacestring=starred/$USER
  separator=/
  curdate=$(system.getcurrentdate)
  newbranch="${currentbranch/$searchstring/$replacestring}/$curdate"
  echo $newbranch
  # create new backup branch
  git checkout -b $newbranch
  # go back to our branch
  git checkout $currentbranch
}

function git.getbugnumberfrombranch() {
  local branchname=$1
  if string.isemptyorblank $branchname
  then
    branchname=$(git.getcurrentbranch)
  fi

  # Just in case the branch name contains an uppercase BEL
  branchname=$(string.simplereplace $branchname "BEL" "bel")
  # sed syntax : "s,search_string,replace_string,regex_flags" (most other characters allowed as separator instead of ,)
  local bugnumber=$(echo $branchname | sed -En "s,.*/(and|bel|ios)-([[:digit:]]+)/.*,\1-\2,p")
  echo $(string.toupper $bugnumber)
}

function git.commit() {
  local bugnumber=$(git.getbugnumberfrombranch)
  git status
  local message=""
  if string.isnotemptyorblank $1
  then
    message="$bugnumber"": $1"
  else
    message="$bugnumber"": more changes"
  fi

  echo "Adding files in the current directory to staging"
  git add .
  git commit -m "$message"
}

# Return true if a remote branch with a given substring of the branchname exists
function git.remotebranchexists() {
  string.isnotemptyorblank $(git ls-remote --heads origin "$1")
}

function git.localbranchexists() {
  system.commandsucceeds $(git show-ref --quiet refs/heads/$1)
}

# List all branches that are not "backup", "merged" or "archived"
# by default, but lists those ones (backup/merged/archived if you
# pass as argument)
function git.listbranches() {
  if string.isnotemptyorblank $1
  then
    git branch | grep $1
  else
    git branch | grep -v -e "backup/" -e "merged/" -e "archived/"
  fi
}

# Delete all merged branches
function git.deletemerged() {
  read -p "Are you sure you want to delete all merged branches? Press any key to continue. Press Ctrl+C to cancel."
  # We could have just used git branch --merged
  # that would actually list all branches that are merged
  # even without our naming convention
  git branch | grep 'merged/' | xargs git branch -D
}

# Creates a patch for the latest commit in your branch
function git.patchlatestcommit() {
  git.patchcommit "HEAD" "$@"
}

# Creates a patch for the specified commit in your branch
function git.patchcommit() {
  # Commit SHA1 id sent as argument. -1 tells git to patch only the last 1 commit.
  local commitId=$1
  local message="$2"
  local optionalFlag="$3"
  local path=$(git.getpatchfilepath "$message" "$optionalFlag")
  system.createfileifdoesnotexist $path

  git format-patch --filename-max-length 256 -1 $commitId --stdout > "$path"
  echo "Patch file created at $path"
}

function git.getbranchnamehyphened() {
  local currentbranch=$(git.getcurrentbranch)
  # remove the username for brevity
  currentbranch=$(string.simplereplace $currentbranch "$USER/" "")
  # replace slashes with hyphens
  echo $(string.simplereplace $currentbranch "/" "-")
}

function git.getpatchfilepath() {
  local dir="."
  local message="$1"
  local optionalFlag="$2"
  if string.isnotemptyorblank $GIT_PATCH_DIR
  then
    dir="$GIT_PATCH_DIR"
  fi

  if string.isnotemptyorblank "$message"
  then
    message=$(string.simplereplace "$message" " " "-")
  fi

  if string.isemptyorblank "$optionalFlag"
  then
    if string.equals "$message" "useful" || string.equals "$message" "--useful" || string.equals "$message" "-u" || string.equals "$message" "pending" || string.equals "$message" "--pending" || string.equals "$message" "-p"
    then
      optionalFlag="$message"
      message=""
    fi
  fi

  local curdate=$(system.getcurrentdate)
  local bugNumber=$(git.getbugnumberfrombranch)
  local outFileName=$(git.getbranchnamehyphened)
  local directoryPath="$dir"

  if string.equals $optionalFlag "useful" || string.equals $optionalFlag "--useful" || string.equals $optionalFlag "-u"
  then
    # This is a general useful patch, so we neither want to store
    # it in a Bug number folder nor want to use bug number in the
    # patch file name.
    bugNumber=""
    outFileName=""
    directoryPath="$directoryPath/useful_patches"
  elif string.equals "$message" "pending" || string.equals "$message" "--pending" || string.equals "$message" "-p"
  then
    bugNumber=""
    outFileName=""
    directoryPath="$directoryPath/pending_to_merge"
  fi

  if string.isnotemptyorblank $bugNumber
  then
    directoryPath="$directoryPath/$bugNumber"

    # Since we're creating this file in a directory
    # containing the bug number folder, we don't need
    # that again in this path. Remove bug number from
    local bugNumberStr=$bugNumber
    if ! string.isemptyorblank $bugNumberStr
    then
      bugNumberStr=$(string.tolower $bugNumberStr)
      bugNumberStr="$bugNumberStr-"
      outFileName=$(string.simplereplace "$outFileName" "$bugNumberStr" "")
    fi
  fi

  if string.isnotemptyorblank $message
  then
    if string.isnotemptyorblank $outFileName
    then
      outFileName=$outFileName-$message
    else
      outFileName=$message
    fi
  fi

  outFileName="$outFileName-$curdate.patch"
  echo "$directoryPath/$outFileName"
}

# Make copy of the current branch to work on
# (which is a little different from taking a backup that
# you don't intend to use for actual work)
# Wouldn't make "copy" of a "copy" correctly according to
# our current nomenclature.
function git.makecopy() {
  local currentbranch=$(git.getcurrentbranch)
  local bugNumber=$(string.tolower $(git.getbugnumberfrombranch))
  local searchstring=$bugNumber
  local replacestring=$bugNumber/copy
  local additionalNotes=""
  local newbranch=$currentbranch
  if string.isemptyorblank $bugNumber
  then
    searchstring="/"
    replacestring="/copy/"
  fi

  if ! string.contains $currentbranch "$bugNumber/copy" # already contains the word copy
  then
    newbranch=${currentbranch/$searchstring/$replacestring}
  fi

  searchstring="copy"
  local foldername=""
  if string.isnotemptyorblank $1
  then
    # Replace spaces with hyphens
    additionalNotes=$(string.simplereplace "$1" " " "-")
    foldername=$additionalNotes
  else
    declare -i loopvar=1
    replacestring="copy/$loopvar"
    local tempbranchname=${newbranch/$searchstring/$replacestring}
    while git.localbranchexists $tempbranchname
    do
      loopvar=$((loopvar+1))
      replacestring="copy/$loopvar"
      tempbranchname=${newbranch/$searchstring/$replacestring}
    done
    foldername=$loopvar
  fi

  replacestring="copy/$foldername"
  newbranch=${newbranch/$searchstring/$replacestring}

  echo "Calling git checkout -b $newbranch"
  git checkout -b "$newbranch"
}


# Return the branch name/tag this branch is based off
# e.g. master, lsb/master etc. For this, the branch must have
# been created using checkoutfrommaster / checkoutfromlsbmaster etc. commands
function git.getbasebranchname() {
  # Check if there was a remote prefix
  # passed. Only use for branch names, not tag names.
  local remoteprefix=""
  if string.isnotemptyorblank $1
  then
    remoteprefix="$1/"
  fi

  if git.branchislsbmasterbased
  then
    echo "$LSB_MASTER"
  elif git.branchislsbreleasebased
  then
    echo "$LSB_CURRENT_RELEASE"
  elif git.branchismasterbased
  then
    echo "$remoteprefix""master"
  elif git.branchisreleasebased
  then
    echo "$remoteprefix""$CURRENT_RELEASE"
  else
    echo "" # Can't find out.
  fi
}

# Create a patch of uncommitted changes with *LOCAL* HEAD
function git.patchuncommittedchanges() {
  local message="$1"
  local optionalFlag="$2"
  local path=$(git.getpatchfilepath "$message" "$optionalFlag")
  system.createfileifdoesnotexist $path
  git diff HEAD > "$path"
  echo "Patch file created at $path"
}



# Create a patch of all the committed/uncommitted changes
# and compare with the remote origin master / lsb/master
# *** CAUTION ToDo: Doesn't handle new files as of now. ***
function git.patchallchanges() {
  echo "Refreshing tags..."
  git fetch origin --tags --force --prune
  local path=$(git.getpatchfilepath "$@")
  system.createfileifdoesnotexist $path
  git diff "$(git.getbasebranchname origin)" > "$path"
  echo "Patch file created at $path"
}

# Applies a patch and creates .rej files for the changes
# that it could not apply.
function git.applypatch() {
  git apply --reject --whitespace=fix "$1" # patch file path
}

# Pass the remote name : e.g. "origin" / others.
function git.setupstream() {
  local remoteName="$1"
  local branchNameToPush="$2"
  if string.isemptyorblank $remoteName
  then
    remoteName="origin"
  fi

  if string.isemptyorblank $branchNameToPush
  then
    branchNameToPush="$(git.getcurrentbranch)"
  fi

  local newUpstream="$remoteName"/"$branchNameToPush"
  git push --set-upstream "$remoteName" "$branchNameToPush"
}

function git.unsetupstream() {
  git branch --unset-upstream
}

# Checkout the branch that was checked out just before
# the current one. As expected, calling it twice should
# bring you back to the same branch.
function git.checkoutpreviousbranch() {
  git checkout -
}

function git.deletecurrentbranch() {
	local currentbranch=$(git.getcurrentbranch)
	read -p "Are you sure you want to delete the current branch ($currentbranch)? Press any key to continue. Press Ctrl+C to cancel."
	git.checkoutpreviousbranch
	git branch -D $currentbranch
}

function git.setglobalignorefile() {
	if string.isemptyorblank $1
	then
		git config --global core.excludesfile $globalgitignorefile
	else
		git config --global core.excludesfile $1
	fi
}

# Given a commit SHA1 id, finds out the
# id of the merge commit in the given branch. Default
# branch is master
function git.getmergecommit() {
  if string.isemptyorblank $(which git-get-merge)
  then
    echo "git-get-merge utility not found. Please install from https://github.com/jianli/git-get-merge"
    return 1
  fi

  git-get-merge "$@"
}

function git.deletebranch() {
  local branchToDelete="$1"
  if string.isemptyorblank "$branchToDelete" || string.equals "$(git.getcurrentbranch)" "$branchToDelete"
  then
    git.deletecurrentbranch
    return 0
  fi

  if general.inputyesorno "Are you sure you want to delete the branch"
  then
    echo "calling git branch -D $1"
    git branch -D "$1"
  fi
}

# to be called like `if git.isvalidcommitid <commitId>`; then .... fi
function git.isvalidcommitid() {
  local commitId="$1"
  git cat-file -t $commitId 2>/dev/null | grep -q commit
}

function git.copyfilesinlatestcommit() {
  git.copyfilesincommit $(git.getlatestcommitid) "$@"
}

function __replaceinvalidfilenamecharacters() {
  local filename="$1"
  local replacementchar="$2"
  if string.isemptyorblank "$replacementchar"
  then
    replacementchar="-"
  fi

  filename=$(string.simplereplace "$filename" " " "$replacementchar")
  filename=$(string.simplereplace "$filename" "/" "$replacementchar")
  filename=$(string.simplereplace "$filename" "\\" "$replacementchar")
  filename=$(string.simplereplace "$filename" ":" "$replacementchar")
  filename=$(string.simplereplace "$filename" "\*" "$replacementchar")
  filename=$(string.simplereplace "$filename" "\?" "$replacementchar")
  filename=$(string.simplereplace "$filename" "\"" "$replacementchar")
  filename=$(string.simplereplace "$filename" "<" "$replacementchar")
  filename=$(string.simplereplace "$filename" ">" "$replacementchar")
  filename=$(string.simplereplace "$filename" "|" "$replacementchar")
  filename=$(string.trim "$filename")
  echo "$filename"
}

# Copies all the files in the given commit to the given output directory
# by maintaining the exact folder structure for copying later
function git.copyfilesincommit() {
  local commitID="$1"
  local rootDirectory="$2"

  if ! git.isvalidcommitid "$commitID"
  then
    echo "Syntax: git.copyfilesincommit <commitId> <rootDirectory>"
    return 1
  fi

  if string.isemptyorblank "$rootDirectory"
  then
    local commitMessageFirstLine="$(git log -1 --pretty=%B $commitID | head -n 1)"
    commitMessageFirstLine=$(string.trim "$commitMessageFirstLine" 30)
    commitMessageFirstLine=$(__replaceinvalidfilenamecharacters "$commitMessageFirstLine")
    rootDirectory="$GIT_FILES_WITH_FOLDER_STRUCTURE_DIR/$commitMessageFirstLine-$commitID"
    echo "No root directory provided, using $rootDirectory for writing files"
  fi

  if ! system.direxists "$rootDirectory"
  then
    echo "Provided root directory doesn't exist, creating now."
    mkdir -p "$rootDirectory"
    if ! system.waslastcommandsuccessful
    then
      print_error "Could not create input root directory. Please give a valid directory path."
      return 1
    fi
  fi

  # Get the list of files changed or added in the commit
  files=$(git diff-tree --no-commit-id --name-only -r $commitID)

  # Loop through each file and copy it to the root directory, preserving the directory structure
  for file in $files; do
      mkdir -p "$rootDirectory/$(dirname $file)"
      cp "$file" "$rootDirectory/$file"
  done

  local totalFilesSuccessfullyCreated=$(string.trim $(system.countfilesrecursively "$rootDirectory"))
  echo "Total $totalFilesSuccessfullyCreated files from commit $commitID have been copied to $rootDirectory"
}

# Paste files from a source directory to the destination directory
# maintaining the folder structure. If destination directory is not
# provided, assumes newton project root directory.
# The source and target directories are not copied themselves, only
# their contents are.
# CAUTION: Overwrites files in the destination directory if they
# already exist.
function git.pastefileswithfolderstructure() {
  local sourceDirectory="$1"
  local destinationDirectory="$2"

  if string.isemptyorblank "$sourceDirectory" || ! system.direxists "$sourceDirectory"
  then
    print_error "Please provide a valid source directory containing files with folder structure."
    return 1
  fi

  if string.isemptyorblank "$destinationDirectory" || ! system.direxists "$destinationDirectory"
  then
    # Assume newton project root directory
    echo "Pasting files (overwrite enabled) maintaining file directory structure into $REPO_NEWTON directory"
    destinationDirectory="$REPO_NEWTON"
  fi

  if git.hasUncommittedChanges
  then
    print_error "You have uncommitted changes in the current repository. Please commit or stash them before pasting files."
    return 1
  fi

  # Copy files while preserving the directory structure
  rsync -av --quiet "$sourceDirectory/" "$destinationDirectory/"

  local totalFilesSuccessfullyCopied=$(string.trim $(system.countfilesrecursively "$sourceDirectory"))
  echo "Total $totalFilesSuccessfullyCopied files from $sourceDirectory have been copied to $destinationDirectory"
}

# Function to find all branches that have changed a given file
# Written using LLM Coding agents, seems to work fine,
# but please be careful.
git.findbrancheswithfilechanges() {
    local file_path=""
    local time_limit=""
    local branch_pattern=""
    local remote_only=false
    local local_only=false
    local max_branches=""
    local verbose=false
    local help=false

    # Parse command line arguments
    while [[ $# -gt 0 ]]; do
        case $1 in
            -f|--file)
                file_path="$2"
                shift 2
                ;;
            -t|--time|--since)
                time_limit="$2"
                shift 2
                ;;
            -p|--pattern)
                branch_pattern="$2"
                shift 2
                ;;
            -r|--remote-only)
                remote_only=true
                shift
                ;;
            -l|--local-only)
                local_only=true
                shift
                ;;
            -m|--max-branches)
                max_branches="$2"
                shift 2
                ;;
            -v|--verbose)
                verbose=true
                shift
                ;;
            -h|--help)
                help=true
                shift
                ;;
            -*)
                echo "Error: Unknown option $1" >&2
                return 1
                ;;
            *)
                if [[ -z "$file_path" ]]; then
                    file_path="$1"
                else
                    echo "Error: Multiple file paths specified" >&2
                    return 1
                fi
                shift
                ;;
        esac
    done

    # Show help if requested
    if [[ "$help" == true ]]; then
        cat << 'EOF'
Usage: git.findbrancheswithfilechanges [OPTIONS] <file_path>

Find all branches that have changes to a specific file.

OPTIONS:
    -f, --file FILE         File path to search for (can also be passed as positional arg)
    -t, --time, --since TIME    Limit search to commits since TIME (e.g., "2 weeks ago", "2023-01-01")
    -p, --pattern PATTERN   Only check branches matching PATTERN (shell glob pattern)
    -r, --remote-only       Only check remote branches
    -l, --local-only        Only check local branches
    -m, --max-branches NUM  Stop after checking NUM branches
    -v, --verbose           Show progress and additional information
    -h, --help              Show this help message

EXAMPLES:
    git.findbrancheswithfilechanges src/main.c
    git.findbrancheswithfilechanges -f src/main.c -t "1 month ago"
    git.findbrancheswithfilechanges -f README.md -p "feature/*" -v
    git.findbrancheswithfilechanges -f config.json -r -m 50

TIME FORMAT:
    Git-compatible time formats like "2 weeks ago", "2023-01-01", "yesterday"
EOF
        return 0
    fi

    # Validate required arguments
    if [[ -z "$file_path" ]]; then
        echo "Error: File path is required" >&2
        echo "Use -h or --help for usage information" >&2
        return 1
    fi

    # Check if we're in a git repository
    if ! git rev-parse --git-dir >/dev/null 2>&1; then
        echo "Error: Not in a git repository" >&2
        return 1
    fi

    # Validate conflicting options
    if [[ "$remote_only" == true && "$local_only" == true ]]; then
        echo "Error: Cannot specify both --remote-only and --local-only" >&2
        return 1
    fi

    # Validate max_branches is a number if specified
    if [[ -n "$max_branches" ]] && ! [[ "$max_branches" =~ ^[0-9]+$ ]]; then
        echo "Error: --max-branches must be a positive integer" >&2
        return 1
    fi

    [[ "$verbose" == true ]] && echo "Searching for branches with changes to: $file_path"

    # Build git branch command based on options
    local branch_cmd="git branch"
    if [[ "$remote_only" == true ]]; then
        branch_cmd="git branch -r"
    elif [[ "$local_only" == true ]]; then
        branch_cmd="git branch"
    else
        branch_cmd="git branch -a"
    fi

    # Get list of branches and clean them up
    local branches
    branches=$($branch_cmd | sed 's/^[* ] *//' | grep -v '^HEAD ->' | grep -v '(HEAD detached')

    if [[ -z "$branches" ]]; then
        echo "No branches found" >&2
        return 1
    fi

    # Apply branch pattern filter if specified
    if [[ -n "$branch_pattern" ]]; then
        # Use bash 3.2 compatible pattern matching
        local filtered_branches=""
        while IFS= read -r branch; do
            # Remove origin/ prefix for pattern matching if it's a remote branch
            local branch_name="$branch"
            if [[ "$branch" =~ ^origin/ ]]; then
                branch_name="${branch#origin/}"
            fi

            # Use case statement for pattern matching (bash 3.2 compatible)
            case "$branch_name" in
                $branch_pattern)
                    if [[ -n "$filtered_branches" ]]; then
                        filtered_branches="$filtered_branches"$'\n'"$branch"
                    else
                        filtered_branches="$branch"
                    fi
                    ;;
            esac
        done <<< "$branches"
        branches="$filtered_branches"

        if [[ -z "$branches" ]]; then
            echo "No branches match pattern: $branch_pattern" >&2
            return 1
        fi
    fi

    local found_branches=()
    local checked_count=0
    local total_branches
    total_branches=$(echo "$branches" | wc -l | tr -d ' ')

    [[ "$verbose" == true ]] && echo "Checking $total_branches branches..."

    # Check each branch
    while IFS= read -r branch; do
        [[ -z "$branch" ]] && continue

        checked_count=$((checked_count + 1))

        # Check max_branches limit
        if [[ -n "$max_branches" ]] && [[ $checked_count -gt $max_branches ]]; then
            [[ "$verbose" == true ]] && echo "Reached maximum branch limit ($max_branches)"
            break
        fi

        [[ "$verbose" == true ]] && echo "Checking branch $checked_count/$total_branches: $branch"

        # Build git log command with time limit if specified
        local log_cmd="git log --oneline"
        if [[ -n "$time_limit" ]]; then
            log_cmd="$log_cmd --since=\"$time_limit\""
        fi
        log_cmd="$log_cmd -- \"$file_path\""

        # Check if branch has commits affecting the file
        local commits
        commits=$(git log --oneline ${time_limit:+--since="$time_limit"} "$branch" -- "$file_path" 2>/dev/null)
        local exit_code=$?

        if [[ $exit_code -eq 0 ]] && [[ -n "$commits" ]]; then
            found_branches+=("$branch")
            if [[ "$verbose" == true ]]; then
                local commit_count
                commit_count=$(echo "$commits" | wc -l | tr -d ' ')
                echo "  ✓ Found $commit_count commit(s) in $branch"
            fi
        elif [[ $exit_code -ne 0 ]]; then
            [[ "$verbose" == true ]] && echo "  ! Error checking branch $branch (may not exist)"
        fi
    done <<< "$branches"

    # Output results
    if [[ ${#found_branches[@]} -eq 0 ]]; then
        echo "No branches found with changes to $file_path"
        if [[ -n "$time_limit" ]]; then
            echo "(searched commits since: $time_limit)"
        fi
        return 0
    else
        echo "Found ${#found_branches[@]} branch(es) with changes to $file_path:"
        if [[ -n "$time_limit" ]]; then
            echo "(commits since: $time_limit)"
        fi
        echo

        # Sort branches for consistent output
        printf '%s\n' "${found_branches[@]}" | sort
        return 0
    fi
}




# Show your git branches sorted by latest commit
# Credit to this alias goes to this Slack conversation : https://onshape.slack.com/archives/C18HMGX32/p1495031914762665
alias gb='cur=$(git rev-parse --abbrev-ref HEAD); prev=$(git rev-parse --abbrev-ref @{-1}); git for-each-ref --sort=committerdate refs/heads/ --format="%(color:reset)  %(refname:short)|%(color:black bold)%(committerdate:relative)%(color:reset)" | column -ts"|" | sed -e "s,  ${cur} ,$(tput setaf 2)$(tput bold)* ${cur} ," | sed -e "s,  ${prev} ,$(tput setaf 3)$(tput bold)  ${prev} ,";tput sgr0;'
alias stoptrackingfile='git.skipworktree'
alias starttrackingfile='git.unskipworktree'
alias git.currentbranch='git.getcurrentbranch'
alias git.copybranch='git.makecopy'
alias git.history='gb'
alias git.branchhistory='git.history'
alias opengitglobalignorefile='edit $globalgitignorefile'
alias openglobalgitignorefile='opengitglobalignorefile'
alias opengitignorefile='opengitglobalignorefile'
alias openglobalgitconfigfile='edit $globalgitconfigfile'
alias opengitconfigfile='openglobalgitconfigfile'
alias git.getparentcommit='git.getmergecommit'
alias git.findparentcommit='git.getmergecommit'
alias git.findmergecommit='git.getmergecommit'
alias git.parentcommit='git.getmergecommit'
alias git.mergecommit='git.getmergecommit'
alias git.createfolderstructurefromcommit='git.copyfilesincommit'
